/**
 * Packaging contract: every file the published `exports` map promises must
 * actually land in the npm tarball. v1.0.0 shipped with `src/` but no `types/`
 * — the exports map pointed each subpath at a `./types/*.d.mts` that was never
 * packed, so consumers under `checkJs`/strict resolved the imports to untyped
 * `.mjs` and `tsc` failed. The declarations are generated by the `prepack`
 * lifecycle script (`build:types`) and listed in `files`; drop either and the
 * tarball silently loses its types again.
 *
 * `npm pack --dry-run --json` runs `prepack` exactly as a real publish does and
 * reports the resulting file list, so this asserts against what would actually
 * be shipped rather than the working tree. Each `types`/`default` target in the
 * exports map must appear in that list; the `.d.mts` half is asserted non-empty
 * so the check can never pass vacuously if the type targets disappear.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const repoRoot = execFileSync("git", ["rev-parse", "--show-toplevel"], {
  encoding: "utf8",
}).trim();

const pkg = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);

// The conditions in each exports subpath that name a shipped file. `import`,
// `require`, and `node` would join these if added later; enumerating the live
// set keeps the guard tracking the real map instead of a hard-coded pair.
const FILE_CONDITIONS = ["types", "default", "import", "require", "node"];

/** The condition → file map for one subpath, with the leading `./` stripped. */
function conditionFiles(target) {
  // A subpath may name its file directly instead of through a conditions
  // object (`"./credential-names": "./…/credential-names.json"`). Iterating
  // such a string with Object.entries yields character indices, none of which
  // is a file condition — so the subpath would be skipped and its file left
  // unguarded, which is the fail-open this branch closes.
  if (typeof target === "string")
    return { default: target.replace(/^\.\//, "") };
  return Object.fromEntries(
    Object.entries(target)
      .filter(([condition]) => FILE_CONDITIONS.includes(condition))
      .map(([condition, value]) => [condition, value.replace(/^\.\//, "")]),
  );
}

/** Subpath targets, split by condition kind. */
function exportedFiles() {
  const types = [];
  const runtime = [];
  for (const target of Object.values(pkg.exports)) {
    for (const [condition, file] of Object.entries(conditionFiles(target)))
      (condition === "types" ? types : runtime).push(file);
  }
  return { types, runtime };
}

// Pack list as it would publish: `--dry-run` runs `prepack` (building the
// declarations) without writing a tarball; `--json` gives a stable file list.
function packedFiles() {
  const out = execFileSync(
    "npm",
    ["pack", "--dry-run", "--json", "--ignore-scripts=false"],
    { cwd: repoRoot, encoding: "utf8" },
  );
  // `prepack` runs `pnpm build:types`, and pnpm's deps check writes its
  // "Progress: resolved …" line to STDOUT — so npm's JSON is not necessarily the
  // whole stream. Slice from the array start, or the test reds on a first
  // invocation for a reason that has nothing to do with the packaging contract.
  const start = out.indexOf("[");
  assert.notEqual(start, -1, `npm pack emitted no JSON array:\n${out}`);
  return new Set(JSON.parse(out.slice(start))[0].files.map((f) => f.path));
}

describe("packaging contract: exports map vs. published tarball", () => {
  const { types, runtime } = exportedFiles();
  const packed = packedFiles();

  it("ships a declaration for every exports subpath (non-vacuous)", () => {
    assert.ok(
      types.length > 0,
      "no `types` conditions found in exports — the guard would pass vacuously",
    );
    const missing = types.filter((f) => !packed.has(f));
    assert.deepEqual(
      missing,
      [],
      `exports promise .d.mts files the tarball does not ship: ${missing.join(", ")}. ` +
        "Did `prepack`/`build:types` or the `types` entry in `files` get dropped?",
    );
  });

  it("ships the runtime entry for every exports subpath", () => {
    assert.ok(runtime.length > 0, "no runtime conditions found in exports");
    const missing = runtime.filter((f) => !packed.has(f));
    assert.deepEqual(
      missing,
      [],
      `exports promise runtime files the tarball does not ship: ${missing.join(", ")}`,
    );
  });

  // Top-level docs a consumer reaches for from an installed copy: the license,
  // the readme, the threat model, and — so a vulnerability is reported privately
  // rather than filed in the open — the disclosure policy. Each must be listed in
  // `files` AND actually land in the tarball; a literal entry that doesn't pack
  // (typo, renamed/deleted file) is the regression this guards.
  it("ships the user-facing top-level docs", () => {
    const docs = ["LICENSE", "README.md", "THREAT-MODEL.md", "SECURITY.md"];
    for (const doc of docs)
      assert.ok(
        pkg.files.includes(doc),
        `package.json "files" is missing ${doc}`,
      );
    const missing = docs.filter((f) => !packed.has(f));
    assert.deepEqual(
      missing,
      [],
      `top-level docs listed in "files" but not packed: ${missing.join(", ")}`,
    );
  });
});
