/**
 * Behavioural gate for the hook-binary provisioner: on the hosts it exists for
 * (no usable node), it downloads the release asset for the installed plugin
 * version, verifies it against the committed digest manifest BEFORE anything
 * executes it, and installs it where the launcher looks. Every case drives the
 * real script under a curated PATH — the network is a curl stub whose "server"
 * is a fixture file, so what each test observes is the script's own behaviour:
 * the URL it asked for, the file it installed (or refused to), and its mode.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  accessSync,
  constants,
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ASSET_PREFIX, PLATFORMS } from "../scripts/build-hook-binaries.mjs";

const ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const PLUGIN_DIR = join(ROOT, "plugin");

/** A scratch dir removed when the test finishes. */
function scratch(t) {
  const dir = mkdtempSync(join(tmpdir(), "agent-sanitizer-provision-test-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return dir;
}

/** The platform the stubbed `uname` reports, and the asset that names. */
const STUB_PLATFORM = ["Linux", "x86_64"];
const ASSET = "agent-sanitizer-hooks-linux-x64";

/**
 * Stage the plugin tree with a manifest pinning `assetBytes` for this
 * platform, plus a fixture "release asset" the curl stub serves. Returns the
 * staged pieces.
 */
function stageProvisionable(
  t,
  { assetBytes = "FAKE HOOK BINARY\n", asset = ASSET } = {},
) {
  const dir = scratch(t);
  const plugin = join(dir, "plugin");
  cpSync(PLUGIN_DIR, plugin, { recursive: true });
  const fixture = join(dir, "release-asset");
  writeFileSync(fixture, assetBytes);
  const digest = createHash("sha256").update(assetBytes).digest("hex");
  const manifest = join(plugin, "dist", "hooks", "hook-binaries.sha256");
  writeFileSync(
    manifest,
    "# GENERATED by plugin/scripts/build-hook-binaries.mjs — do not edit by hand.\n" +
      "# repository=example-owner/example-repo\n" +
      "# bun=0.0.0\n" +
      "# bundle=0000000000000000000000000000000000000000000000000000000000000000\n" +
      `${digest}  ${asset}\n`,
  );
  return { dir, plugin, fixture, manifest, data: join(dir, "data") };
}

/**
 * A curated PATH: the real shell utilities the script legitimately needs, a
 * stubbed `uname` pinning the platform, and a stubbed `curl` that "downloads"
 * the fixture while logging its argv — so no test touches the network and the
 * requested URL is observable. `omit` drops commands to model a bare host.
 */
function provisionPath(
  t,
  fixture,
  { omit = [], uname = STUB_PLATFORM, downloader = "curl" } = {},
) {
  const dir = join(scratch(t), "bin");
  mkdirSync(dir, { recursive: true });
  for (const cmd of [
    "bash",
    "sh",
    "dirname",
    "cat",
    "cmp",
    "cp",
    "chmod",
    "date",
    "mkdir",
    "mktemp",
    "mv",
    "rm",
    "sha256sum",
    "shasum",
  ]) {
    const found = spawnSync("command", ["-v", cmd], {
      shell: true,
      encoding: "utf8",
    }).stdout.trim();
    if (found && !omit.includes(cmd))
      writeFileSync(join(dir, cmd), `#!/bin/sh\nexec ${found} "$@"\n`, {
        mode: 0o755,
      });
  }
  writeFileSync(
    join(dir, "uname"),
    `#!/bin/sh\ncase "$1" in\n-s) echo ${uname[0]} ;;\n-m) echo ${uname[1]} ;;\nesac\n`,
    { mode: 0o755 },
  );
  // One log for whichever downloader the host has, so every assertion about
  // "did it download, and from where" reads the same regardless of which arm
  // of the script ran. curl writes to -o, wget to -O.
  const curlLog = join(dir, "..", "curl-log");
  const outFlag = downloader === "wget" ? "-O" : "-o";
  if (!omit.includes(downloader))
    writeFileSync(
      join(dir, downloader),
      `#!/bin/sh\necho "$@" >>"${curlLog}"\nout=""\nprev=""\nfor a in "$@"; do\n  if [ "$prev" = "${outFlag}" ]; then out="$a"; fi\n  prev="$a"\ndone\ncp "${fixture}" "$out"\n`,
      { mode: 0o755 },
    );
  return { path: dir, curlLog };
}

/** Run the staged provisioner with a hermetic environment. */
function provision(staged, pathDir, env = {}) {
  return spawnSync(
    "bash",
    [join(staged.plugin, "scripts", "provision-hook-binary.sh"), staged.data],
    {
      encoding: "utf8",
      cwd: tmpdir(),
      env: {
        PATH: pathDir,
        HOME: staged.dir,
        TMPDIR: staged.dir,
        // The node search must not find the runner's own node: these tests
        // model the host class the provisioner exists for.
        _AGENT_SANITIZER_NODE_SEARCH: "0",
        ...env,
      },
    },
  );
}

test("downloads the release asset, verifies it, and installs it executable", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 0, res.stderr);
  assert.match(res.stderr, /hook binary provisioned/);

  const binary = join(staged.data, "hook-binary", "agent-sanitizer-hooks");
  assert.equal(readFileSync(binary, "utf8"), "FAKE HOOK BINARY\n");
  accessSync(binary, constants.X_OK);
  // Owner-only: every hook in the session execs this file, so anything that
  // could write it would have code execution in each of them.
  assert.equal(statSync(binary).mode & 0o777, 0o700);
  assert.equal(statSync(join(staged.data, "hook-binary")).mode & 0o777, 0o700);

  // The URL is derived from the manifest's repository slug and the plugin
  // manifest's own version — read here through JSON.parse, which holds the
  // script's bash extraction to the real parser's answer.
  const { version } = JSON.parse(
    readFileSync(join(staged.plugin, ".claude-plugin", "plugin.json"), "utf8"),
  );
  const requested = readFileSync(curlLog, "utf8").trim().split(" ").at(-1);
  assert.equal(
    requested,
    `https://github.com/example-owner/example-repo/releases/download/v${version}/${ASSET}`,
  );
});

test("a second session with the same manifest downloads nothing", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  assert.equal(provision(staged, path).status, 0);
  const downloadsAfterFirst = readFileSync(curlLog, "utf8").trim().split("\n");
  assert.equal(downloadsAfterFirst.length, 1);
  const res = provision(staged, path);
  assert.equal(res.status, 0, res.stderr);
  assert.equal(res.stderr, "");
  assert.equal(
    readFileSync(curlLog, "utf8").trim().split("\n").length,
    1,
    "the idempotent fast path re-downloaded the binary",
  );
});

test("a changed manifest re-provisions even though a node is available", (t) => {
  // The launcher PREFERS an existing binary, so a plugin update that moves the
  // manifest must refresh it — an adequate node is no excuse to keep serving
  // stale sanitizer code.
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture);
  // Install on a node-less host first — with no binary yet, an adequate node
  // legitimately skips provisioning altogether.
  assert.equal(provision(staged, path).status, 0);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v22.10.0\n", { mode: 0o755 });

  const updated = "UPDATED HOOK BINARY\n";
  writeFileSync(staged.fixture, updated);
  writeFileSync(
    staged.manifest,
    readFileSync(staged.manifest, "utf8").replace(
      /^[0-9a-f]{64}/m,
      createHash("sha256").update(updated).digest("hex"),
    ),
  );
  const res = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(
    readFileSync(
      join(staged.data, "hook-binary", "agent-sanitizer-hooks"),
      "utf8",
    ),
    updated,
  );
});

test("refuses to install a download whose digest does not match the manifest", (t) => {
  const staged = stageProvisionable(t);
  // The "release" serves different bytes than the manifest pins — a tampered
  // or truncated download, or a checkout ahead of its latest release.
  writeFileSync(staged.fixture, "NOT WHAT THE MANIFEST PINS\n");
  const { path } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /refusing to install/);
  const dir = join(staged.data, "hook-binary");
  assert.ok(
    !existsSync(join(dir, "agent-sanitizer-hooks")),
    "an unverified binary was installed",
  );
  // The partial download must not linger where anything could mistake it for
  // an artifact worth trusting later.
  assert.ok(!existsSync(join(dir, ".agent-sanitizer-hooks.download")));
});

test("AGENT_SANITIZER_HOOK_BINARY=0 provisions nothing", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path, { AGENT_SANITIZER_HOOK_BINARY: "0" });
  assert.equal(res.status, 0);
  assert.equal(res.stderr, "");
  assert.ok(!existsSync(curlLog), "the opt-out still downloaded");
});

test("a host whose node search succeeds skips the download — until =1 forces it", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v22.10.0\n", { mode: 0o755 });
  const skipped = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(skipped.status, 0, skipped.stderr);
  assert.ok(!existsSync(curlLog), "an adequate node should have skipped it");
  // Non-vacuity for the skip: the same host with the knob forced DOES download.
  const forced = provision(staged, path, {
    AGENT_SANITIZER_NODE: node,
    AGENT_SANITIZER_HOOK_BINARY: "1",
  });
  assert.equal(forced.status, 0, forced.stderr);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("a below-floor node does not count as adequate", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v18.19.0\n", { mode: 0o755 });
  const res = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("an unsupported platform exits silently", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture, {
    uname: ["FreeBSD", "amd64"],
  });
  const res = provision(staged, path);
  assert.equal(res.status, 0);
  // Silent by design: warning every session start of a host the release never
  // covered is alert fatigue, and the node path serves it exactly as before.
  assert.equal(res.stderr, "");
  assert.ok(!existsSync(curlLog));
});

test("no downloader at all is an advisory failure that names the consequence", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture, { omit: ["curl"] });
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /neither curl nor wget/);
  assert.match(res.stderr, /DEGRADED/);
});

test("no digest tool means no install, not an unverified one", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture, {
    omit: ["sha256sum", "shasum"],
  });
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /cannot be verified/);
  assert.ok(
    !existsSync(join(staged.data, "hook-binary", "agent-sanitizer-hooks")),
  );
});

test("a missing manifest refuses to provision", (t) => {
  const staged = stageProvisionable(t);
  rmSync(staged.manifest);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /reinstall the plugin/);
  assert.ok(!existsSync(curlLog));
});

test("a slow download reports against the one-time setup budget", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture);
  // Threshold 0 rather than a real overrun: what is under test is that this
  // script measures and reports at all, and with the advice that fits a
  // download — the shared default names an installer, which is advice about
  // the wrong step here.
  const res = provision(staged, path, {
    _AGENT_SANITIZER_SLOW_PROVISION_MS: "0",
  });
  assert.equal(res.status, 0, res.stderr);
  assert.match(
    res.stderr,
    /PERFORMANCE: one-time setup \(hook binary download\)/,
  );
  assert.match(res.stderr, /~100 MB/);
  // The install budget, not the per-call one: a ~100 MB transfer charged to a
  // 1s hook budget would report on every cold session and name the wrong cost.
  assert.equal(res.stderr.includes("hook took"), false, res.stderr);
});

test("a fast download says nothing about timing", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  // Non-vacuity for the case above: with the real threshold in force the same
  // run is silent, so it observes the report and not just any stderr.
  assert.equal(res.status, 0, res.stderr);
  assert.equal(res.stderr.includes("PERFORMANCE"), false, res.stderr);
});

test("a missing shared provisioning lib refuses to provision", (t) => {
  const staged = stageProvisionable(t);
  rmSync(join(staged.plugin, "scripts", "lib", "provision-common.sh"));
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  // It aborts AT the missing source, naming the file: under `set -u` the first
  // thing the lib was to define aborts with `provision_begin: command not
  // found`, which names nothing an operator can act on, and nothing is
  // downloaded on the way there.
  assert.equal(res.status, 1);
  assert.match(res.stderr, /provision-common\.sh is missing/);
  assert.match(res.stderr, /reinstall the plugin/);
  assert.ok(!existsSync(curlLog));
});

test("a missing timing lib degrades to an untimed download, not to failure", (t) => {
  const staged = stageProvisionable(t);
  rmSync(join(staged.plugin, "scripts", "lib", "hook-timing.sh"));
  const { path } = provisionPath(t, staged.fixture);
  const res = provision(staged, path, {
    _AGENT_SANITIZER_SLOW_PROVISION_MS: "0",
  });
  // A host that can still download must still download: under
  // `set -euo pipefail` a non-zero from the timing arm would turn a missing
  // stopwatch into a host left on the node path the binary exists to replace.
  assert.equal(res.status, 0, res.stderr);
  assert.match(res.stderr, /hook-timing\.sh is missing/);
  assert.match(res.stderr, /hook binary provisioned/);
  // Nothing pretends to have measured: the threshold is 0 here, so a live
  // timer would report on this very run.
  assert.equal(res.stderr.includes("PERFORMANCE"), false, res.stderr);
});

test("a binary that lands un-executable is not reported as provisioned", (t) => {
  const staged = stageProvisionable(t);
  // chmod is the only thing that makes the download executable, so a no-op one
  // reproduces an install whose every command exits 0 while leaving nothing
  // runnable — the state the stamps written just above the check would
  // otherwise record as "provisioned from this manifest".
  const { path } = provisionPath(t, staged.fixture);
  writeFileSync(join(path, "chmod"), "#!/bin/sh\nexit 0\n", { mode: 0o755 });
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /install finished but .* is not an executable file/);
  assert.equal(
    res.stderr.includes("hook binary provisioned"),
    false,
    res.stderr,
  );
});

// What `uname -s`/`-m` report on each platform the release carries a binary
// for. A platform the script's `case` cannot name is a platform whose users
// silently keep the node dependency the binary exists to remove, so every key
// of PLATFORMS is driven through the real dispatch below.
const UNAME_BY_PLATFORM = {
  "darwin-arm64": [["Darwin", "arm64"]],
  "darwin-x64": [["Darwin", "x86_64"]],
  "linux-x64": [["Linux", "x86_64"]],
  "linux-arm64": [
    ["Linux", "aarch64"],
    ["Linux", "arm64"],
  ],
};

test("every platform the manifest covers resolves to its own release asset", async (t) => {
  assert.deepEqual(
    Object.keys(UNAME_BY_PLATFORM).sort(),
    Object.keys(PLATFORMS).sort(),
  );
  for (const [platform, unames] of Object.entries(UNAME_BY_PLATFORM)) {
    for (const uname of unames) {
      await t.test(`${uname.join(" ")} → ${platform}`, (sub) => {
        const asset = `${ASSET_PREFIX}${platform}`;
        const staged = stageProvisionable(sub, { asset });
        const { path, curlLog } = provisionPath(sub, staged.fixture, { uname });
        const res = provision(staged, path);
        assert.equal(res.status, 0, res.stderr);
        const { version } = JSON.parse(
          readFileSync(
            join(staged.plugin, ".claude-plugin", "plugin.json"),
            "utf8",
          ),
        );
        const requested = readFileSync(curlLog, "utf8")
          .trim()
          .split(" ")
          .at(-1);
        assert.equal(
          requested,
          `https://github.com/example-owner/example-repo/releases/download/v${version}/${asset}`,
        );
      });
    }
  }
});

test("a host with only wget downloads through it", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture, {
    downloader: "wget",
  });
  const res = provision(staged, path);
  assert.equal(res.status, 0, res.stderr);
  assert.equal(
    readFileSync(join(staged.data, "hook-binary", "agent-sanitizer-hooks"), {
      encoding: "utf8",
    }),
    "FAKE HOOK BINARY\n",
  );
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("a rejected download is not re-fetched on the next session", (t) => {
  // Re-downloading ~100 MB every session start only to re-reject it is pure
  // waste: the (manifest, version) pair that failed will fail identically
  // until one of them moves.
  const staged = stageProvisionable(t);
  writeFileSync(staged.fixture, "NOT WHAT THE MANIFEST PINS\n");
  const { path, curlLog } = provisionPath(t, staged.fixture);
  assert.equal(provision(staged, path).status, 1);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);

  const second = provision(staged, path);
  assert.equal(second.status, 1);
  assert.match(second.stderr, /already failed digest verification/);
  // The repeat is deliberately quiet: this state heals on the next release, so
  // the loud refusal wording belongs only on the session that discovered it.
  assert.doesNotMatch(second.stderr, /DEGRADED|refusing to install/);
  assert.equal(
    readFileSync(curlLog, "utf8").trim().split("\n").length,
    1,
    "the rejected asset was downloaded a second time",
  );

  // The cache is scoped to that pair, not permanent: a manifest that moves
  // (a plugin update) retries, and here the release now matches.
  writeFileSync(staged.fixture, "FIXED HOOK BINARY\n");
  writeFileSync(
    staged.manifest,
    readFileSync(staged.manifest, "utf8").replace(
      /^[0-9a-f]{64}/m,
      createHash("sha256").update("FIXED HOOK BINARY\n").digest("hex"),
    ),
  );
  const third = provision(staged, path);
  assert.equal(third.status, 0, third.stderr);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 2);
});

test("a failed download stays retryable — no reject stamp is written", (t) => {
  // The most common real path: a tree released moments ago has no assets
  // attached yet. Unlike a digest mismatch, a network failure says nothing
  // about whether the release's bytes match, so caching it would strand the
  // host until the NEXT release even once the assets appear.
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const workingCurl = readFileSync(join(path, "curl"), "utf8");
  writeFileSync(
    join(path, "curl"),
    `#!/bin/sh\necho "$@" >>"${curlLog}"\nexit 22\n`,
    { mode: 0o755 },
  );
  const first = provision(staged, path);
  assert.equal(first.status, 1);
  assert.match(first.stderr, /failed \(exit 22\)/);
  const dir = join(staged.data, "hook-binary");
  assert.ok(!existsSync(join(dir, "agent-sanitizer-hooks")));
  assert.ok(
    !existsSync(join(dir, ".download-rejected")),
    "a network failure was cached as a rejection, so the next session will not retry",
  );

  // The next session retries, and succeeds once the asset is really there.
  writeFileSync(join(path, "curl"), workingCurl, { mode: 0o755 });
  const second = provision(staged, path);
  assert.equal(second.status, 0, second.stderr);
  assert.equal(
    readFileSync(join(dir, "agent-sanitizer-hooks"), "utf8"),
    "FAKE HOOK BINARY\n",
  );
});

test("a manifest with no digest for THIS platform refuses to provision", (t) => {
  // Distinct from a missing manifest: the file is present and well-formed but
  // carries no line for the running platform, so there is nothing a download
  // could be verified against.
  const staged = stageProvisionable(t, {
    asset: "agent-sanitizer-hooks-darwin-arm64",
  });
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /no usable repository\/digest/);
  assert.ok(
    !existsSync(curlLog),
    "it downloaded with nothing to verify against",
  );
});

test("an unrecognized knob value warns instead of silently meaning auto", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path, { AGENT_SANITIZER_HOOK_BINARY: "false" });
  assert.equal(res.status, 0, res.stderr);
  assert.match(
    res.stderr,
    /AGENT_SANITIZER_HOOK_BINARY=false is not 0, 1 or unset/,
  );
  // It still means auto — the warning is the fix, not a change of behaviour.
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("the staged manifest fixture parses the way the generator's own reader parses it", async (t) => {
  // The fixture above is hand-written; if its shape drifted from what
  // build-hook-binaries.mjs emits, every test here would exercise a format the
  // real provisioner never sees. Holding it to the generator's parser keeps
  // the suite honest about which format it proves.
  const { parseManifest } = await import("../scripts/build-hook-binaries.mjs");
  const staged = stageProvisionable(t);
  const parsed = parseManifest(readFileSync(staged.manifest, "utf8"));
  assert.equal(parsed.repository, "example-owner/example-repo");
  assert.equal(
    parsed.digests["linux-x64"],
    createHash("sha256").update("FAKE HOOK BINARY\n").digest("hex"),
  );
});
