/**
 * Behavioural gate for the hook-binary provisioner: on the hosts it exists for
 * (no usable node), it downloads the release asset for the installed plugin
 * version, verifies it against the committed digest manifest BEFORE anything
 * executes it, and installs it where the launcher looks. Every case drives the
 * real script under a curated PATH — the network is a curl stub whose "server"
 * is a fixture file, so what each test observes is the script's own behaviour:
 * the URL it asked for, the file it installed (or refused to), and its mode.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  accessSync,
  constants,
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const PLUGIN_DIR = join(ROOT, "plugin");

/** A scratch dir removed when the test finishes. */
function scratch(t) {
  const dir = mkdtempSync(join(tmpdir(), "agent-sanitizer-provision-test-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return dir;
}

/** The platform the stubbed `uname` reports, and the asset that names. */
const STUB_PLATFORM = ["Linux", "x86_64"];
const ASSET = "agent-sanitizer-hooks-linux-x64";

/**
 * Stage the plugin tree with a manifest pinning `assetBytes` for this
 * platform, plus a fixture "release asset" the curl stub serves. Returns the
 * staged pieces.
 */
function stageProvisionable(t, { assetBytes = "FAKE HOOK BINARY\n" } = {}) {
  const dir = scratch(t);
  const plugin = join(dir, "plugin");
  cpSync(PLUGIN_DIR, plugin, { recursive: true });
  const fixture = join(dir, "release-asset");
  writeFileSync(fixture, assetBytes);
  const digest = createHash("sha256").update(assetBytes).digest("hex");
  const manifest = join(plugin, "dist", "hooks", "hook-binaries.sha256");
  writeFileSync(
    manifest,
    "# GENERATED by plugin/scripts/build-hook-binaries.mjs — do not edit by hand.\n" +
      "# repository=example-owner/example-repo\n" +
      "# bun=0.0.0\n" +
      "# bundle=0000000000000000000000000000000000000000000000000000000000000000\n" +
      `${digest}  ${ASSET}\n`,
  );
  return { dir, plugin, fixture, manifest, data: join(dir, "data") };
}

/**
 * A curated PATH: the real shell utilities the script legitimately needs, a
 * stubbed `uname` pinning the platform, and a stubbed `curl` that "downloads"
 * the fixture while logging its argv — so no test touches the network and the
 * requested URL is observable. `omit` drops commands to model a bare host.
 */
function provisionPath(t, fixture, { omit = [], uname = STUB_PLATFORM } = {}) {
  const dir = join(scratch(t), "bin");
  mkdirSync(dir, { recursive: true });
  for (const cmd of [
    "bash",
    "sh",
    "dirname",
    "cat",
    "cmp",
    "cp",
    "chmod",
    "date",
    "mkdir",
    "mv",
    "rm",
    "sha256sum",
    "shasum",
  ]) {
    const found = spawnSync("command", ["-v", cmd], {
      shell: true,
      encoding: "utf8",
    }).stdout.trim();
    if (found && !omit.includes(cmd))
      writeFileSync(join(dir, cmd), `#!/bin/sh\nexec ${found} "$@"\n`, {
        mode: 0o755,
      });
  }
  writeFileSync(
    join(dir, "uname"),
    `#!/bin/sh\ncase "$1" in\n-s) echo ${uname[0]} ;;\n-m) echo ${uname[1]} ;;\nesac\n`,
    { mode: 0o755 },
  );
  const curlLog = join(dir, "..", "curl-log");
  if (!omit.includes("curl"))
    writeFileSync(
      join(dir, "curl"),
      `#!/bin/sh\necho "$@" >>"${curlLog}"\nout=""\nprev=""\nfor a in "$@"; do\n  if [ "$prev" = "-o" ]; then out="$a"; fi\n  prev="$a"\ndone\ncp "${fixture}" "$out"\n`,
      { mode: 0o755 },
    );
  return { path: dir, curlLog };
}

/** Run the staged provisioner with a hermetic environment. */
function provision(staged, pathDir, env = {}) {
  return spawnSync(
    "bash",
    [join(staged.plugin, "scripts", "provision-hook-binary.sh"), staged.data],
    {
      encoding: "utf8",
      cwd: tmpdir(),
      env: {
        PATH: pathDir,
        HOME: staged.dir,
        TMPDIR: staged.dir,
        // The node search must not find the runner's own node: these tests
        // model the host class the provisioner exists for.
        _AGENT_SANITIZER_NODE_SEARCH: "0",
        ...env,
      },
    },
  );
}

test("downloads the release asset, verifies it, and installs it executable", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 0, res.stderr);
  assert.match(res.stderr, /hook binary provisioned/);

  const binary = join(staged.data, "hook-binary", "agent-sanitizer-hooks");
  assert.equal(readFileSync(binary, "utf8"), "FAKE HOOK BINARY\n");
  accessSync(binary, constants.X_OK);

  // The URL is derived from the manifest's repository slug and the plugin
  // manifest's own version — read here through JSON.parse, which holds the
  // script's bash extraction to the real parser's answer.
  const { version } = JSON.parse(
    readFileSync(join(staged.plugin, ".claude-plugin", "plugin.json"), "utf8"),
  );
  const requested = readFileSync(curlLog, "utf8").trim().split(" ").at(-1);
  assert.equal(
    requested,
    `https://github.com/example-owner/example-repo/releases/download/v${version}/${ASSET}`,
  );
});

test("a second session with the same manifest downloads nothing", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  assert.equal(provision(staged, path).status, 0);
  const downloadsAfterFirst = readFileSync(curlLog, "utf8").trim().split("\n");
  assert.equal(downloadsAfterFirst.length, 1);
  const res = provision(staged, path);
  assert.equal(res.status, 0, res.stderr);
  assert.equal(res.stderr, "");
  assert.equal(
    readFileSync(curlLog, "utf8").trim().split("\n").length,
    1,
    "the idempotent fast path re-downloaded the binary",
  );
});

test("a changed manifest re-provisions even though a node is available", (t) => {
  // The launcher PREFERS an existing binary, so a plugin update that moves the
  // manifest must refresh it — an adequate node is no excuse to keep serving
  // stale sanitizer code.
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture);
  // Install on a node-less host first — with no binary yet, an adequate node
  // legitimately skips provisioning altogether.
  assert.equal(provision(staged, path).status, 0);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v22.10.0\n", { mode: 0o755 });

  const updated = "UPDATED HOOK BINARY\n";
  writeFileSync(staged.fixture, updated);
  writeFileSync(
    staged.manifest,
    readFileSync(staged.manifest, "utf8").replace(
      /^[0-9a-f]{64}/m,
      createHash("sha256").update(updated).digest("hex"),
    ),
  );
  const res = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(
    readFileSync(
      join(staged.data, "hook-binary", "agent-sanitizer-hooks"),
      "utf8",
    ),
    updated,
  );
});

test("refuses to install a download whose digest does not match the manifest", (t) => {
  const staged = stageProvisionable(t);
  // The "release" serves different bytes than the manifest pins — a tampered
  // or truncated download, or a checkout ahead of its latest release.
  writeFileSync(staged.fixture, "NOT WHAT THE MANIFEST PINS\n");
  const { path } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /refusing to install/);
  const dir = join(staged.data, "hook-binary");
  assert.ok(
    !existsSync(join(dir, "agent-sanitizer-hooks")),
    "an unverified binary was installed",
  );
  // The partial download must not linger where anything could mistake it for
  // an artifact worth trusting later.
  assert.ok(!existsSync(join(dir, ".agent-sanitizer-hooks.download")));
});

test("AGENT_SANITIZER_HOOK_BINARY=0 provisions nothing", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path, { AGENT_SANITIZER_HOOK_BINARY: "0" });
  assert.equal(res.status, 0);
  assert.equal(res.stderr, "");
  assert.ok(!existsSync(curlLog), "the opt-out still downloaded");
});

test("a host whose node search succeeds skips the download — until =1 forces it", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v22.10.0\n", { mode: 0o755 });
  const skipped = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(skipped.status, 0, skipped.stderr);
  assert.ok(!existsSync(curlLog), "an adequate node should have skipped it");
  // Non-vacuity for the skip: the same host with the knob forced DOES download.
  const forced = provision(staged, path, {
    AGENT_SANITIZER_NODE: node,
    AGENT_SANITIZER_HOOK_BINARY: "1",
  });
  assert.equal(forced.status, 0, forced.stderr);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("a below-floor node does not count as adequate", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const node = join(scratch(t), "node");
  writeFileSync(node, "#!/bin/sh\necho v18.19.0\n", { mode: 0o755 });
  const res = provision(staged, path, { AGENT_SANITIZER_NODE: node });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(readFileSync(curlLog, "utf8").trim().split("\n").length, 1);
});

test("an unsupported platform exits silently", (t) => {
  const staged = stageProvisionable(t);
  const { path, curlLog } = provisionPath(t, staged.fixture, {
    uname: ["FreeBSD", "amd64"],
  });
  const res = provision(staged, path);
  assert.equal(res.status, 0);
  // Silent by design: warning every session start of a host the release never
  // covered is alert fatigue, and the node path serves it exactly as before.
  assert.equal(res.stderr, "");
  assert.ok(!existsSync(curlLog));
});

test("no downloader at all is an advisory failure that names the consequence", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture, { omit: ["curl"] });
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /neither curl nor wget/);
  assert.match(res.stderr, /DEGRADED/);
});

test("no digest tool means no install, not an unverified one", (t) => {
  const staged = stageProvisionable(t);
  const { path } = provisionPath(t, staged.fixture, {
    omit: ["sha256sum", "shasum"],
  });
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /cannot be verified/);
  assert.ok(
    !existsSync(join(staged.data, "hook-binary", "agent-sanitizer-hooks")),
  );
});

test("a missing manifest refuses to provision", (t) => {
  const staged = stageProvisionable(t);
  rmSync(staged.manifest);
  const { path, curlLog } = provisionPath(t, staged.fixture);
  const res = provision(staged, path);
  assert.equal(res.status, 1);
  assert.match(res.stderr, /reinstall the plugin/);
  assert.ok(!existsSync(curlLog));
});

test("the staged manifest fixture parses the way the generator's own reader parses it", async (t) => {
  // The fixture above is hand-written; if its shape drifted from what
  // build-hook-binaries.mjs emits, every test here would exercise a format the
  // real provisioner never sees. Holding it to the generator's parser keeps
  // the suite honest about which format it proves.
  const { parseManifest } = await import("../scripts/build-hook-binaries.mjs");
  const staged = stageProvisionable(t);
  const parsed = parseManifest(readFileSync(staged.manifest, "utf8"));
  assert.equal(parsed.repository, "example-owner/example-repo");
  assert.equal(
    parsed.digests["linux-x64"],
    createHash("sha256").update("FAKE HOOK BINARY\n").digest("hex"),
  );
});
