/**
 * Build the Claude Code plugin's shipped artifact: one self-contained ESM bundle
 * with every package inlined, so an installed plugin needs no node_modules.
 *
 * The engine is resolved from the REGISTRY, never from this repo's own `src/`:
 * the `sanitizer-engine` devDependency is an npm alias pinning a published
 * agent-sanitizer version, and the esbuild alias below maps the hooks' canonical
 * `agent-sanitizer` specifiers onto it. That is what keeps the committed bundle
 * stable across ordinary source changes — it only moves when the pin moves.
 */
import { existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  bundleHardened,
  bundleTarget,
} from "../../scripts/lib/bundle-esbuild.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Repo root (this script lives at plugin/scripts/). */
const ROOT = resolve(__dirname, "..", "..");

/**
 * This artifact's entry in the repo-wide bundle list, which owns the esbuild
 * configuration and the runtime-require hardening.
 */
const TARGET = bundleTarget("plugin-hooks");

/** The hook sources the bundle is built from. */
export const PLUGIN_ENTRY = TARGET.entry;

/** Committed artifact path. */
export const BUNDLE_PATH = TARGET.outfile;

/**
 * Direct requirement the lock is compiled FROM: the PyPI half of the engine
 * pin. Generated here (offline, from package.json) so the network-free build
 * still owns the pin; `plugin/scripts/lock-redactor-deps.mjs` resolves it into
 * the committed lock.
 */
export const REQUIREMENTS_IN_PATH = join(ROOT, "plugin", "requirements.in");

/**
 * The fully-resolved, hash-pinned lock both the zipapp build and the
 * SessionStart provisioner install from. Compiled, never hand-written.
 */
export const REQUIREMENTS_LOCK_PATH = join(ROOT, "plugin", "requirements.txt");

// The packages inlined into the bundle. esbuild prefixes each inlined module
// with a `// <path>` comment, and for a pnpm dep that path embeds the
// content-addressed store hash, which varies with the store layout across
// environments and would make a committed bundle differ from a CI rebuild for no
// real reason.
const INLINED_PACKAGES = [
  "agent-control-plane-core",
  "agent-sanitizer",
  "namespace-guard",
];

/**
 * The published engine version the plugin is pinned to, read from the
 * `sanitizer-engine` npm alias in package.json. Throws when the alias is absent
 * or not in `npm:agent-sanitizer@<version>` form — a plugin built against an
 * unknown engine must fail the build, never ship an unpinned bundle.
 * @param {string} [packageJsonText]
 * @returns {string}
 */
export function enginePin(packageJsonText) {
  const pkg = JSON.parse(
    packageJsonText ?? readFileSync(join(ROOT, "package.json"), "utf-8"),
  );
  const spec = pkg.devDependencies?.["sanitizer-engine"];
  const match = /^npm:agent-sanitizer@(?<version>\d+\.\d+\.\d+)$/.exec(
    spec ?? "",
  );
  if (!match)
    throw new Error(
      `package.json: devDependencies.sanitizer-engine must be "npm:agent-sanitizer@<x.y.z>", got ${JSON.stringify(spec)}`,
    );
  // Read the numeric index, not `match.groups.version`: the named group keeps the
  // pattern readable, but `groups` is optional in the type so only the indexed
  // read is statically a string.
  return match[1];
}

/**
 * The generated requirements.in body: the PyPI half of the same pin, so the
 * redactor daemon the plugin provisions matches the engine it bundled.
 * @param {string} [version]
 * @returns {string}
 */
export function redactorRequirements(version = enginePin()) {
  return (
    "# GENERATED by plugin/scripts/build-plugin.mjs from the sanitizer-engine\n" +
    "# pin in package.json — do not edit by hand.\n" +
    "#\n" +
    "# This is the INPUT to the lock, not what gets installed. Compile it into\n" +
    "# plugin/requirements.txt with `node plugin/scripts/lock-redactor-deps.mjs`\n" +
    "# whenever this file changes.\n" +
    `agent-sanitizer[secrets]==${version}\n`
  );
}

/**
 * The `agent-sanitizer` version a compiled lock pins, or null when the lock
 * does not pin it at all. Read with an anchored line match rather than a
 * substring scan so a `# via agent-sanitizer` provenance comment (or the
 * `agent-sanitizer[secrets]` extra spelling in the header's echoed command
 * line) cannot masquerade as the pin.
 * @param {string} lockText
 * @returns {string | null}
 */
export function lockedEngineVersion(lockText) {
  const match = /^agent-sanitizer==(?<version>\d+\.\d+\.\d+)(?: |\\|$)/m.exec(
    lockText,
  );
  return match ? match[1] : null;
}

/**
 * Bundle the plugin entry into a self-contained ESM string, then normalize the
 * pnpm store paths in esbuild's module labels so the reproducibility test
 * compares actual code. The esbuild configuration itself — including the
 * runtime-`require()` inlining and the build-time assertion that none survive —
 * lives in `scripts/lib/bundle-esbuild.mjs`, shared with the wheel's CLI bundle.
 * @returns {Promise<string>}
 */
export async function bundlePluginHook() {
  const version = enginePin();
  const text = await bundleHardened(TARGET);
  return (
    `/**\n * GENERATED by plugin/scripts/build-plugin.mjs — do not edit by hand.\n` +
    ` * Built against agent-sanitizer@${version} from the npm registry.\n */\n` +
    normalizeModulePaths(text)
  );
}

/**
 * Rewrite esbuild's `// <path>` module labels for the inlined packages to a
 * stable, package-relative form (`// <pkg>/<rest>`), so the reproducibility gate
 * compares actual code, not pnpm store paths. Done with plain string splits (no
 * regex) over the fixed store markers; the entry's own repo-relative label is
 * already stable.
 * @param {string} text
 * @returns {string}
 */
export function normalizeModulePaths(text) {
  return text
    .split("\n")
    .map((line) => {
      if (!line.startsWith("// ")) return line;
      for (const pkg of INLINED_PACKAGES) {
        const marker = `/node_modules/${pkg}/`;
        const idx = line.indexOf(marker);
        if (idx !== -1) return `// ${pkg}/${line.slice(idx + marker.length)}`;
      }
      return line;
    })
    .join("\n");
}

/**
 * The installed root of `specifier`: resolve its main entry, then walk up to the
 * directory holding its package.json. Resolving "<pkg>/package.json" directly
 * would be simpler but these packages restrict their `exports` map, which makes
 * that subpath unresolvable — and the resolution must go through the ESM
 * resolver, since some of them declare only an `import` condition.
 * @param {string} specifier
 * @returns {string}
 */
function packageRoot(specifier) {
  let dir = dirname(fileURLToPath(import.meta.resolve(specifier)));
  for (;;) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir)
      throw new Error(`no package.json above the entry of ${specifier}`);
    dir = parent;
  }
}

/**
 * The installed directory of each package the un-bundled hooks import by bare
 * specifier, so a test can stage a node_modules that resolves them (the repo
 * installs the engine under its alias, not its own name).
 * @returns {Record<string, string>}
 */
export function packageDirs() {
  return {
    "agent-sanitizer": packageRoot("sanitizer-engine"),
    "agent-control-plane-core": packageRoot("agent-control-plane-core"),
    "namespace-guard": packageRoot("namespace-guard"),
  };
}

/**
 * Write the bundle and requirements.in, returning whether either changed.
 * requirements.txt is NOT written here: compiling it resolves the dependency
 * tree over the network, and this build is the offline reproducibility rebuild.
 * @returns {Promise<boolean>}
 */
async function writeArtifacts() {
  const bundle = await bundlePluginHook();
  const requirements = redactorRequirements();
  mkdirSync(dirname(BUNDLE_PATH), { recursive: true });
  let changed = false;
  for (const [path, content] of [
    [BUNDLE_PATH, bundle],
    [REQUIREMENTS_IN_PATH, requirements],
  ]) {
    let existing;
    try {
      existing = readFileSync(path, "utf-8");
    } catch {
      existing = null;
    }
    if (existing === content) continue;
    writeFileSync(path, content);
    changed = true;
  }
  return changed;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const changed = await writeArtifacts();
  process.stdout.write(
    changed
      ? `plugin artifacts regenerated (engine ${enginePin()})\n`
      : `plugin artifacts already current (engine ${enginePin()})\n`,
  );
}

// kill-test touch
