/**
 * Build the Claude Code plugin's shipped artifact: one self-contained ESM bundle
 * with every package inlined, so an installed plugin needs no node_modules.
 *
 * Both halves of the plugin are built from THIS tree: the hooks' canonical
 * `agent-sanitizer` specifiers resolve to the repo itself (`link:.`), and the
 * zipapp beside them installs `agent_sanitizer` from `python/`. Neither carries
 * a published version, so the two cannot ship disagreeing engines and the
 * committed bundle is always the code the suite ran against. The cost is that
 * every `src/` change rewrites the artifact — `.hooks/rebuild-plugin-artifacts`
 * regenerates and stages it so a stale bundle cannot be committed.
 */
import { existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parse as parseToml } from "smol-toml";

import {
  bundleHardened,
  bundleTarget,
} from "../../scripts/lib/bundle-esbuild.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Repo root (this script lives at plugin/scripts/). */
const ROOT = resolve(__dirname, "..", "..");

/**
 * This artifact's entry in the repo-wide bundle list, which owns the esbuild
 * configuration and the runtime-require hardening.
 */
const TARGET = bundleTarget("plugin-hooks");

/** The hook sources the bundle is built from. */
export const PLUGIN_ENTRY = TARGET.entry;

/** Committed artifact path. */
export const BUNDLE_PATH = TARGET.outfile;

/**
 * Direct requirements the lock is compiled FROM: the redactor daemon's
 * third-party dependencies. Generated here (offline, from python/pyproject.toml)
 * so the network-free build owns them; `plugin/scripts/lock-redactor-deps.mjs`
 * resolves them into the committed lock.
 */
export const REQUIREMENTS_IN_PATH = join(ROOT, "plugin", "requirements.in");

/**
 * The fully-resolved, hash-pinned lock both the zipapp build and the
 * SessionStart provisioner install from. Compiled, never hand-written.
 */
export const REQUIREMENTS_LOCK_PATH = join(ROOT, "plugin", "requirements.txt");

// The packages inlined into the bundle. esbuild prefixes each inlined module
// with a `// <path>` comment, and for a pnpm dep that path embeds the
// content-addressed store hash, which varies with the store layout across
// environments and would make a committed bundle differ from a CI rebuild for no
// real reason.
const INLINED_PACKAGES = ["agent-control-plane-core", "namespace-guard"];

/**
 * The third-party requirements the redactor daemon needs, read from the extra
 * that declares them in `python/pyproject.toml`.
 *
 * `agent_sanitizer` itself is deliberately absent: the zipapp installs it from
 * THIS tree, so the daemon and the JS bundle beside it are the same commit by
 * construction. Naming a published version here is what would let the two
 * halves drift, and there is no version that could name an unreleased HEAD.
 * Everything that does come from PyPI stays hash-pinned through the lock.
 * @param {string} [pyprojectText]
 * @returns {string}
 */
export function redactorRequirements(pyprojectText) {
  const text =
    pyprojectText ??
    readFileSync(join(ROOT, "python", "pyproject.toml"), "utf-8");
  // Cast at the parse boundary: smol-toml types every value as TomlValue, so
  // reading a known table path off it needs the shape stated once, here, rather
  // than a non-null assertion at each hop.
  const parsed = /** @type {any} */ (parseToml(text));
  const extras = parsed.project?.["optional-dependencies"]?.secrets;
  if (!Array.isArray(extras) || extras.length === 0)
    throw new Error(
      "python/pyproject.toml: [project.optional-dependencies].secrets must " +
        `list the daemon's dependencies, got ${JSON.stringify(extras)}`,
    );
  return (
    "# GENERATED by plugin/scripts/build-plugin.mjs from the `secrets` extra in\n" +
    "# python/pyproject.toml — do not edit by hand.\n" +
    "#\n" +
    "# This is the INPUT to the lock, not what gets installed. Compile it into\n" +
    "# plugin/requirements.txt with `node plugin/scripts/lock-redactor-deps.mjs`\n" +
    "# whenever this file changes.\n" +
    `${extras.join("\n")}\n`
  );
}

/**
 * The `agent-sanitizer` version a compiled lock pins, or null when it does not
 * pin one — which is the only state the zipapp build accepts, since the engine
 * comes from this tree rather than from PyPI.
 *
 * Read with an anchored line match rather than a substring scan so a `# via
 * agent-sanitizer` provenance comment (or an `agent-sanitizer[secrets]` spelling
 * echoed in the header's command line) cannot masquerade as a pin.
 * @param {string} lockText
 * @returns {string | null}
 */
export function lockedEngineVersion(lockText) {
  const match = /^agent-sanitizer==(?<version>\d+\.\d+\.\d+)(?: |\\|$)/m.exec(
    lockText,
  );
  return match ? match[1] : null;
}

/**
 * Bundle the plugin entry into a self-contained ESM string, then normalize the
 * pnpm store paths in esbuild's module labels so the reproducibility test
 * compares actual code. The esbuild configuration itself — including the
 * runtime-`require()` inlining and the build-time assertion that none survive —
 * lives in `scripts/lib/bundle-esbuild.mjs`, shared with the wheel's CLI bundle.
 * @returns {Promise<string>}
 */
export async function bundlePluginHook() {
  const text = await bundleHardened(TARGET);
  return (
    `/**\n * GENERATED by plugin/scripts/build-plugin.mjs — do not edit by hand.\n` +
    ` * Built from this repo's own src/, the tree the test suite runs against.\n */\n` +
    normalizeModulePaths(text)
  );
}

/**
 * Rewrite esbuild's `// <path>` module labels for the inlined packages to a
 * stable, package-relative form (`// <pkg>/<rest>`), so the reproducibility gate
 * compares actual code, not pnpm store paths. Done with plain string splits (no
 * regex) over the fixed store markers; the entry's own repo-relative label is
 * already stable.
 * @param {string} text
 * @returns {string}
 */
export function normalizeModulePaths(text) {
  return text
    .split("\n")
    .map((line) => {
      if (!line.startsWith("// ")) return line;
      for (const pkg of INLINED_PACKAGES) {
        const marker = `/node_modules/${pkg}/`;
        const idx = line.indexOf(marker);
        if (idx !== -1) return `// ${pkg}/${line.slice(idx + marker.length)}`;
      }
      return line;
    })
    .join("\n");
}

/**
 * The installed root of `specifier`: resolve its main entry, then walk up to the
 * directory holding its package.json. Resolving "<pkg>/package.json" directly
 * would be simpler but these packages restrict their `exports` map, which makes
 * that subpath unresolvable — and the resolution must go through the ESM
 * resolver, since some of them declare only an `import` condition.
 * @param {string} specifier
 * @returns {string}
 */
function packageRoot(specifier) {
  let dir = dirname(fileURLToPath(import.meta.resolve(specifier)));
  for (;;) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir)
      throw new Error(`no package.json above the entry of ${specifier}`);
    dir = parent;
  }
}

/**
 * The installed directory of each package the un-bundled hooks import by bare
 * specifier, so a test can stage a node_modules that resolves them.
 * @returns {Record<string, string>}
 */
export function packageDirs() {
  return {
    "agent-sanitizer": packageRoot("agent-sanitizer"),
    "agent-control-plane-core": packageRoot("agent-control-plane-core"),
    "namespace-guard": packageRoot("namespace-guard"),
  };
}

/**
 * Write the bundle and requirements.in, returning whether either changed.
 * requirements.txt is NOT written here: compiling it resolves the dependency
 * tree over the network, and this build is the offline reproducibility rebuild.
 * @returns {Promise<boolean>}
 */
async function writeArtifacts() {
  const bundle = await bundlePluginHook();
  const requirements = redactorRequirements();
  mkdirSync(dirname(BUNDLE_PATH), { recursive: true });
  let changed = false;
  for (const [path, content] of [
    [BUNDLE_PATH, bundle],
    [REQUIREMENTS_IN_PATH, requirements],
  ]) {
    let existing;
    try {
      existing = readFileSync(path, "utf-8");
    } catch {
      existing = null;
    }
    if (existing === content) continue;
    writeFileSync(path, content);
    changed = true;
  }
  return changed;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const changed = await writeArtifacts();
  process.stdout.write(
    changed
      ? "plugin artifacts regenerated from this tree\n"
      : "plugin artifacts already current\n",
  );
}

// kill-test touch
