/**
 * Build the Claude Code plugin's shipped artifact: one self-contained ESM bundle
 * with every package inlined, so an installed plugin needs no node_modules.
 *
 * The engine is resolved from the REGISTRY, never from this repo's own `src/`:
 * the `sanitizer-engine` devDependency is an npm alias pinning a published
 * agent-sanitizer version, and the esbuild alias below maps the hooks' canonical
 * `agent-sanitizer` specifiers onto it. That is what keeps the committed bundle
 * stable across ordinary source changes — it only moves when the pin moves.
 */
import { build } from "esbuild";
import { existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Repo root (this script lives at plugin/scripts/). */
const ROOT = resolve(__dirname, "..", "..");

/** The hook sources the bundle is built from. */
export const PLUGIN_ENTRY = join(ROOT, "claude-hooks", "plugin-hooks.mjs");

/** Committed artifact path. */
export const BUNDLE_PATH = join(
  ROOT,
  "plugin",
  "dist",
  "hooks",
  "plugin-hooks.bundle.mjs",
);

/** Committed Python requirement the SessionStart provisioner installs. */
export const REQUIREMENTS_PATH = join(ROOT, "plugin", "requirements.txt");

// The packages inlined into the bundle. esbuild prefixes each inlined module
// with a `// <path>` comment, and for a pnpm dep that path embeds the
// content-addressed store hash, which varies with the store layout across
// environments and would make a committed bundle differ from a CI rebuild for no
// real reason.
const INLINED_PACKAGES = [
  "agent-control-plane-core",
  "agent-sanitizer",
  "namespace-guard",
];

/**
 * The published engine version the plugin is pinned to, read from the
 * `sanitizer-engine` npm alias in package.json. Throws when the alias is absent
 * or not in `npm:agent-sanitizer@<version>` form — a plugin built against an
 * unknown engine must fail the build, never ship an unpinned bundle.
 * @param {string} [packageJsonText]
 * @returns {string}
 */
export function enginePin(packageJsonText) {
  const pkg = JSON.parse(
    packageJsonText ?? readFileSync(join(ROOT, "package.json"), "utf-8"),
  );
  const spec = pkg.devDependencies?.["sanitizer-engine"];
  const match = /^npm:agent-sanitizer@(?<version>\d+\.\d+\.\d+)$/.exec(
    spec ?? "",
  );
  if (!match)
    throw new Error(
      `package.json: devDependencies.sanitizer-engine must be "npm:agent-sanitizer@<x.y.z>", got ${JSON.stringify(spec)}`,
    );
  // Read the numeric index, not `match.groups.version`: the named group keeps the
  // pattern readable, but `groups` is optional in the type so only the indexed
  // read is statically a string.
  return match[1];
}

/**
 * The generated requirements.txt body: the PyPI half of the same pin, so the
 * redactor daemon the plugin provisions matches the engine it bundled.
 * @param {string} [version]
 * @returns {string}
 */
export function redactorRequirements(version = enginePin()) {
  return (
    "# GENERATED by plugin/scripts/build-plugin.mjs from the sanitizer-engine\n" +
    "# pin in package.json — do not edit by hand.\n" +
    `agent-sanitizer[secrets]==${version}\n`
  );
}

/**
 * Inline the JSON data files that dependencies pull in through
 * `createRequire(import.meta.url)("…json")`.
 *
 * esbuild inlines the surrounding JS but leaves such a require intact, and it
 * then resolves relative to the BUNDLE — `plugin/dist/…`, which an installed
 * plugin does not have. css-tree reaches for its CSS syntax tables this way, so
 * the hook threw `Cannot find module '../data/patch.json'` on the first HTML
 * tool output: Layer 2 failed closed and every WebFetch result was suppressed
 * rather than sanitized.
 *
 * Rewriting each such require into a static import hands the table to esbuild,
 * which inlines it like any other dependency. Written against the PATTERN, not
 * against the two css-tree files that exhibit it today, so a dependency bump
 * that moves the tables is covered — and assertNoRuntimeRequires below fails the
 * build if any survive regardless.
 */
const inlineRuntimeJsonRequires = {
  name: "inline-runtime-json-requires",
  /** @param {import("esbuild").PluginBuild} build */
  setup(build) {
    build.onLoad({ filter: /\.m?js$/, namespace: "file" }, (args) => {
      if (!args.path.includes("node_modules")) return null;
      const source = readFileSync(args.path, "utf8");
      if (!source.includes("createRequire")) return null;
      const calls = [...source.matchAll(/require\((['"])([^'"]+\.json)\1\)/g)];
      if (calls.length === 0) return null;

      /** @type {string[]} */
      const imports = [];
      let contents = source;
      calls.forEach(([call, , specifier], index) => {
        const binding = `__inlinedJson${index}`;
        imports.push(`import ${binding} from ${JSON.stringify(specifier)};`);
        contents = contents.replace(call, binding);
      });
      return {
        contents: `${imports.join("\n")}\n${contents}`,
        loader: "js",
        resolveDir: dirname(args.path),
      };
    });
  },
};

// The one runtime require the artifact may keep: confusableScan resolves
// namespace-guard from the lazy-module registry first and only falls back to
// require() on the host, where a node_modules exists. Every other survivor
// means a file the installed plugin does not ship.
const ALLOWED_RUNTIME_REQUIRES = new Set(["namespace-guard"]);

/**
 * Fail the build on any runtime require the installed plugin could not resolve.
 * This is the general guard: the rewrite above handles the shape we know, and
 * this refuses to ship the shape we do not.
 * @param {string} text
 */
function assertNoRuntimeRequires(text) {
  const survivors = [
    ...new Set(
      [...text.matchAll(/\brequire\d*\((['"])([^'"]+)\1\)/g)].map((m) => m[2]),
    ),
  ].filter((spec) => !ALLOWED_RUNTIME_REQUIRES.has(spec));
  if (survivors.length > 0)
    throw new Error(
      `bundle keeps runtime require() of: ${survivors.join(", ")}. ` +
        "An installed plugin has no node_modules and no sibling data files, so " +
        "these throw on first use. Inline them at build time.",
    );
}

/**
 * Bundle the plugin entry into a self-contained ESM string. Deterministic: no
 * minify (the shipped bytes stay auditable), `node:` builtins left external
 * (present in every target runtime), store paths normalized. esbuild's output
 * for a given version + inputs is byte-stable, which is what lets the
 * reproducibility test compare committed vs freshly built.
 * @returns {Promise<string>}
 */
export async function bundlePluginHook() {
  const version = enginePin();
  const result = await build({
    entryPoints: [PLUGIN_ENTRY],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node22",
    // The hooks import the engine by its canonical name so the same sources are
    // publishable as `agent-sanitizer/claude-hooks`; only the bundle resolves
    // that name to the pinned registry copy.
    alias: { "agent-sanitizer": "sanitizer-engine" },
    // Only Node's own builtins may remain as imports in the artifact; everything
    // else is inlined. A bare (non-node:) import surviving here would mean the
    // installed plugin needs a node_modules — the exact thing this bundle exists
    // to avoid — so keep the external set to builtins only.
    external: ["node:*"],
    minify: false,
    legalComments: "none",
    write: false,
    logLevel: "silent",
    plugins: [inlineRuntimeJsonRequires],
  });
  const [file] = result.outputFiles;
  assertNoRuntimeRequires(file.text);
  return (
    `/**\n * GENERATED by plugin/scripts/build-plugin.mjs — do not edit by hand.\n` +
    ` * Built against agent-sanitizer@${version} from the npm registry.\n */\n` +
    normalizeModulePaths(file.text)
  );
}

/**
 * Rewrite esbuild's `// <path>` module labels for the inlined packages to a
 * stable, package-relative form (`// <pkg>/<rest>`), so the reproducibility gate
 * compares actual code, not pnpm store paths. Done with plain string splits (no
 * regex) over the fixed store markers; the entry's own repo-relative label is
 * already stable.
 * @param {string} text
 * @returns {string}
 */
export function normalizeModulePaths(text) {
  return text
    .split("\n")
    .map((line) => {
      if (!line.startsWith("// ")) return line;
      for (const pkg of INLINED_PACKAGES) {
        const marker = `/node_modules/${pkg}/`;
        const idx = line.indexOf(marker);
        if (idx !== -1) return `// ${pkg}/${line.slice(idx + marker.length)}`;
      }
      return line;
    })
    .join("\n");
}

/**
 * The installed root of `specifier`: resolve its main entry, then walk up to the
 * directory holding its package.json. Resolving "<pkg>/package.json" directly
 * would be simpler but these packages restrict their `exports` map, which makes
 * that subpath unresolvable — and the resolution must go through the ESM
 * resolver, since some of them declare only an `import` condition.
 * @param {string} specifier
 * @returns {string}
 */
function packageRoot(specifier) {
  let dir = dirname(fileURLToPath(import.meta.resolve(specifier)));
  for (;;) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir)
      throw new Error(`no package.json above the entry of ${specifier}`);
    dir = parent;
  }
}

/**
 * The installed directory of each package the un-bundled hooks import by bare
 * specifier, so a test can stage a node_modules that resolves them (the repo
 * installs the engine under its alias, not its own name).
 * @returns {Record<string, string>}
 */
export function packageDirs() {
  return {
    "agent-sanitizer": packageRoot("sanitizer-engine"),
    "agent-control-plane-core": packageRoot("agent-control-plane-core"),
    "namespace-guard": packageRoot("namespace-guard"),
  };
}

/**
 * Write the bundle and requirements.txt, returning whether either changed.
 * @returns {Promise<boolean>}
 */
async function writeArtifacts() {
  const bundle = await bundlePluginHook();
  const requirements = redactorRequirements();
  mkdirSync(dirname(BUNDLE_PATH), { recursive: true });
  let changed = false;
  for (const [path, content] of [
    [BUNDLE_PATH, bundle],
    [REQUIREMENTS_PATH, requirements],
  ]) {
    let existing;
    try {
      existing = readFileSync(path, "utf-8");
    } catch {
      existing = null;
    }
    if (existing === content) continue;
    writeFileSync(path, content);
    changed = true;
  }
  return changed;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const changed = await writeArtifacts();
  process.stdout.write(
    changed
      ? `plugin artifacts regenerated (engine ${enginePin()})\n`
      : `plugin artifacts already current (engine ${enginePin()})\n`,
  );
}

// kill-test touch
