#!/usr/bin/env bash
# `source=` paths below are relative to this script, not to shellcheck's cwd.
# shellcheck source-path=SCRIPTDIR
# SessionStart: provision the self-contained hook binary for this platform, so
# the sanitize hooks can run with no node on the host at all — the session
# shape that defeats the launcher's node search (launchd, cron, CI, a GUI
# launch, where PATH is roughly /usr/bin:/bin and every version manager's rc
# file never ran). The binary is downloaded from this repo's GitHub release for
# the installed plugin version and verified against the committed digest
# manifest before it is ever executed. Failure here is advisory — the launcher
# keeps degrading loudly through its node path until a binary exists.
set -uo pipefail

# "0" opts out of the binary entirely (the launcher honors the same spelling);
# "1" provisions even on a host whose node search succeeds; unset provisions
# only where that search would come up empty, so a host that can already run
# the bundle never pays the ~100 MB download.
if [[ "${AGENT_SANITIZER_HOOK_BINARY:-}" == "0" ]]; then
  exit 0
fi

data_dir="${1:?usage: provision-hook-binary.sh <plugin-data-dir>}"
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
plugin_root="$(cd -- "$script_dir/.." && pwd)"

# Only the platforms the release carries binaries for. Anything else exits
# silently: the node path serves it exactly as before, and a warning on every
# session start of an unsupported host is alert fatigue, not signal.
case "$(uname -s 2>/dev/null)-$(uname -m 2>/dev/null)" in
Darwin-arm64) platform="darwin-arm64" ;;
Darwin-x86_64) platform="darwin-x64" ;;
Linux-x86_64) platform="linux-x64" ;;
Linux-aarch64 | Linux-arm64) platform="linux-arm64" ;;
*) exit 0 ;;
esac

asset="agent-sanitizer-hooks-$platform"
manifest="$plugin_root/dist/hooks/hook-binaries.sha256"
dest_dir="$data_dir/hook-binary"
binary="$dest_dir/agent-sanitizer-hooks"
stamp="$dest_dir/.manifest-installed"
download="$dest_dir/.agent-sanitizer-hooks.download"

# A ~100 MB download can dominate session start, and it blocks under the same
# 1800s harness timeout as every hook — so it reports itself against the
# provisioning budget, not the per-hook one (see lib/hook-timing.sh). The one
# EXIT trap also owns the partial download: no path below may leave one behind
# to be mistaken for a binary.
provision_started_ms=0
if [[ -r "$script_dir/lib/hook-timing.sh" ]]; then
  # shellcheck source=lib/hook-timing.sh
  . "$script_dir/lib/hook-timing.sh"
  provision_started_ms="$(hook_timing_now_ms)"
else
  echo "agent-sanitizer: $script_dir/lib/hook-timing.sh is missing — provisioning timing disabled (reinstall the plugin)" >&2
  report_slow_provision() { :; }
fi
trap 'rm -f -- "$download"; report_slow_provision "hook binary download" "$provision_started_ms"' EXIT

if [[ ! -f "$manifest" ]]; then
  echo "agent-sanitizer: $manifest is missing — the hook binary cannot be verified, so it will not be provisioned (reinstall the plugin)" >&2
  exit 1
fi

# The manifest is generated by plugin/scripts/build-hook-binaries.mjs with a
# fixed shape; read with bash builtins alone because this script must run on a
# PATH as bare as /usr/bin:/bin. plugin/test/provision-hook-binary.test.mjs
# holds this reader to the generator's own parser.
repository=""
expected_digest=""
while IFS= read -r line; do
  case "$line" in
  "# repository="*) repository="${line#"# repository="}" ;;
  *"  $asset") expected_digest="${line%% *}" ;;
  esac
done <"$manifest"
if [[ ! "$repository" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ || ! "$expected_digest" =~ ^[0-9a-f]{64}$ ]]; then
  echo "agent-sanitizer: $manifest carries no usable repository/digest for $asset — the hook binary will not be provisioned (reinstall the plugin)" >&2
  exit 1
fi

# Already provisioned from THIS manifest? The stamp is a copy compared with
# `cmp` (no digest tool needed on the fast path); a plugin update that moves
# the manifest re-provisions even on hosts whose node search succeeds, because
# the launcher prefers an existing binary and must never keep running a stale
# one.
if [[ -x "$binary" ]] && cmp -s "$manifest" "$stamp"; then
  exit 0
fi

# No binary yet: on the default posture, a host whose node search finds a
# runtime the bundle can run needs nothing from us. Missing search libs count
# as "no adequate node" — provisioning is the recovery that costs bandwidth,
# not correctness.
if [[ "${AGENT_SANITIZER_HOOK_BINARY:-}" != "1" && ! -x "$binary" ]]; then
  if [[ -r "$script_dir/lib/node-resolve.sh" && -r "$script_dir/lib/node-floor.sh" ]]; then
    # shellcheck source=lib/node-resolve.sh
    . "$script_dir/lib/node-resolve.sh"
    # shellcheck source=lib/node-floor.sh
    . "$script_dir/lib/node-floor.sh"
    node_bin="$(agent_sanitizer_resolve_node)"
    if [[ -n "$node_bin" && -x "$node_bin" ]] && agent_sanitizer_node_meets_floor "$node_bin"; then
      exit 0
    fi
  fi
fi

version=""
plugin_json="$plugin_root/.claude-plugin/plugin.json"
if [[ -r "$plugin_json" ]]; then
  while IFS= read -r line; do
    case "$line" in
    *'"version"'*)
      version="${line#*\"version\"*:*\"}"
      version="${version%%\"*}"
      break
      ;;
    esac
  done <"$plugin_json"
fi
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "agent-sanitizer: no plugin version found in $plugin_json — cannot pick a release to download the hook binary from (reinstall the plugin)" >&2
  exit 1
fi

url="https://github.com/$repository/releases/download/v$version/$asset"
consequence="the hooks keep using the node runtime search; on a host without node >=22, sanitization stays DEGRADED (failing open unless AGENT_SANITIZER_FAIL_OPEN=0) until a new session provisions the binary."

mkdir -p -- "$dest_dir"
if [[ ! -d "$dest_dir" ]]; then
  echo "agent-sanitizer: cannot create $dest_dir — $consequence" >&2
  exit 1
fi

if command -v curl >/dev/null 2>&1; then
  curl -fsSL --retry 2 --max-time 900 -o "$download" -- "$url"
  fetch_rc=$?
elif command -v wget >/dev/null 2>&1; then
  wget -q -T 900 -O "$download" -- "$url"
  fetch_rc=$?
else
  echo "agent-sanitizer: neither curl nor wget is available — the hook binary cannot be downloaded; $consequence" >&2
  exit 1
fi
if [[ "$fetch_rc" -ne 0 ]]; then
  echo "agent-sanitizer: downloading $url failed (exit $fetch_rc) — $consequence (A tree released moments ago may not have its binaries attached yet; a later session retries.)" >&2
  exit 1
fi

# The verification IS the trust boundary: the download came over the network,
# and this refusal is what blocks a tampered or truncated binary — or one from
# a release that does not match this checkout — from ever being executed. No
# digest tool means no verification, which means no install.
if command -v sha256sum >/dev/null 2>&1; then
  got="$(sha256sum <"$download")"
elif command -v shasum >/dev/null 2>&1; then
  got="$(shasum -a 256 <"$download")"
else
  echo "agent-sanitizer: neither sha256sum nor shasum is available — the downloaded hook binary cannot be verified, so it will not be installed; $consequence" >&2
  exit 1
fi
got="${got%% *}"
if [[ "$got" != "$expected_digest" ]]; then
  echo "agent-sanitizer: $asset from $url hashes to $got, but the committed manifest pins $expected_digest — refusing to install it; $consequence (A checkout ahead of its latest release hits this until the next release; it heals on its own.)" >&2
  exit 1
fi

chmod 755 -- "$download"
mv -f -- "$download" "$binary"
cp -- "$manifest" "$stamp"
echo "agent-sanitizer: hook binary provisioned into $binary — hooks now run with no node dependency" >&2
