import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "coverage/**",
      "types/**",
      "node_modules/**",
      // Worktree scaffolding: a second, gitignored copy of the whole repo, so
      // linting it would double every finding and report them at paths that do
      // not exist on the branch.
      ".claude/worktrees/**",
      "config/**",
      "tests/**",
      // The committed plugin bundle is generated (~1.8 MB of inlined
      // dependencies); the sources it is built from are linted instead.
      "plugin/dist/**",
      // Same for the wheel's CLI bundle: generated by
      // `scripts/bundle-python-cli.mjs` from `bin/` + `src/`, git-ignored, and
      // already excluded from Prettier. Linting it makes `pnpm lint` fail for
      // anyone who has run the bundler locally.
      "python/agent_sanitizer/_bundled/**",
      // Stryker copies the project into a sandbox here during a mutation run and
      // mutates the sources in place; never lint that transient mutated copy.
      ".stryker-tmp/**",
      "reports/**",
      // `uv sync` materializes the Python env here; its vendored JS (regexploit,
      // urllib3) is not ours to lint and fails no-undef under this flat config.
      ".venv/**",
    ],
  },
  js.configs.recommended,
  {
    // Ignoring the automation layer wholesale ("carries its own conventions")
    // would leave `pnpm lint` linting 0 of the ~48 JS files under .github/,
    // .hooks/ and .claude/hooks/ — including four hook modules that run
    // inside a Claude session and three CommonJS scripts that run in CI
    // with a token. Same rules as the library: an unused binding or a
    // typo'd global is not more acceptable in a workflow script.
    files: [
      "src/**/*.mjs",
      "test/**/*.mjs",
      "scripts/**/*.mjs",
      "claude-hooks/**/*.mjs",
      "plugin/scripts/**/*.mjs",
      "plugin/test/**/*.mjs",
      ".github/**/*.mjs",
      ".hooks/**/*.mjs",
      ".claude/hooks/**/*.mjs",
    ],
    languageOptions: {
      // "latest" rather than a pinned year: the hook config modules are loaded
      // with import attributes (`with { type: "json" }`), which no fixed
      // ecmaVersion below 2025 parses.
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "consistent-return": "error",
      // Both shipped bundles broke the same way — a dependency's runtime
      // `require()` survived into the artifact — because each build script made
      // its own bare esbuild call and only one of them carried the mitigation.
      // Routing every build through `scripts/lib/bundle-esbuild.mjs` (which
      // inlines those requires and throws on any survivor) is only an invariant
      // if a new script cannot quietly reach for esbuild itself.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "esbuild",
              message:
                "Import bundleHardened from scripts/lib/bundle-esbuild.mjs instead: a bare esbuild build skips the runtime-require inlining and the build-time guard, which is how the wheel's CLI shipped broken. Add the entry to BUNDLE_TARGETS.",
            },
          ],
        },
      ],
    },
  },
  {
    // `.github/scripts/package.json` declares `"type": "commonjs"`, so the `.js`
    // scripts there are CJS: `require`/`module` are globals, not undefined names.
    files: [".github/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: { ...globals.node },
    },
    rules: { "consistent-return": "error" },
  },
  {
    // The one module allowed to call esbuild directly — it *is* the guard.
    files: ["scripts/lib/**/*.mjs"],
    rules: { "no-restricted-imports": "off" },
  },
);
