/**
 * Invisible-character + ANSI/SGR primitives with no external runtime deps.
 *
 * Removes payload-capable Unicode (general-category Cf format chars, variation
 * selectors, blank-rendering fillers, soft hyphens, interior BOMs) while
 * preserving ZWNJ/ZWJ in genuine linguistic and emoji contexts, and reports
 * which categories were removed. The linguistic carve-out is driven by the
 * generated Unicode Joining_Type / virama tables in ./joining-type.mjs (a
 * sibling data module, not a package), so it decides preservation from the
 * actual cursive-join semantics rather than a hand-rolled script guess.
 */
import { joiningType, isVirama, isBrahmicConsonant } from "./joining-type.mjs";
import { isStandardizedVariant } from "./standardized-variants.mjs";
import { CF_CODEPOINTS } from "./cf-charset.mjs";
import { scanAnsi, TOKEN_KIND } from "./ansi.mjs";

// Unicode's Variation_Selector property, whole: the FE00 run, the Mongolian
// free variation selectors, and the astral E0100 supplement. The Mongolian four
// are general category Mn, so \p{Cf} does not reach them and CF_CODEPOINTS
// carries only U+180E (the vowel SEPARATOR) — without them a run of U+180B..D
// renders as nothing, survives untouched, and counts as VISIBLE length, which
// also widens the preserved-joiner budget.
export const VS = [
  ...Array.from({ length: 16 }, (_, i) => 0xfe00 + i),
  0x180b,
  0x180c,
  0x180d,
  0x180f,
  ...Array.from({ length: 240 }, (_, i) => 0xe0100 + i),
]
  .map((codePoint) => String.fromCodePoint(codePoint))
  .join("");

// Combining marks (general category Mn) that carry NO advance width \u2014 they
// render as nothing on their own, so a run of them is a hidden channel exactly
// like a zero-width Cf char, yet \p{Cf} misses them (they are Mn). Strictly
// enumerated, one reason per entry, because MOST Mn marks DO have visible width
// (accents, vowel signs) and must never be stripped \u2014 only these zero-advance
// ones qualify. Driven as an SSOT so the test iterates one case per member.
//   U+034F COMBINING GRAPHEME JOINER \u2014 invisible; affects only collation/shaping
//   U+17B4 KHMER VOWEL INHERENT AQ   \u2014 zero-width inherent vowel, renders blank
//   U+17B5 KHMER VOWEL INHERENT AA   \u2014 zero-width inherent vowel, renders blank
export const ZERO_WIDTH_MN = "\u034F\u17B4\u17B5";

// Code points that render blank / zero-width but are NOT general category Cf,
// so the \p{Cf} check below misses them: the Hangul fillers (category Lo,
// U+115F/U+1160/U+3164/U+FFA0), the Braille blank pattern (category So,
// U+2800), and the zero-width combining marks above (category Mn). A run of any
// of these carries a hidden payload exactly as zero-widths do.
export const BLANK_NON_CF = "\u115F\u1160\u3164\uFFA0\u2800" + ZERO_WIDTH_MN;

const REGEX_FLAGS = "gu";

// A regex character-class source (`[…]`, `u`-flag) matching EXACTLY the pinned
// Cf code points in CF_CODEPOINTS — the version-locked stand-in for a live
// `\p{Cf}` test. Node (U17) and the CPython interpreter the Python port runs on
// (often U14/U15) disagree on `\p{Cf}`, so testing `\p{Cf}` live here would strip
// a DIFFERENT set than the port and let a key spliced with a code point in the
// version delta (e.g. U+13439) escape the older-Unicode layer. Reading the pinned
// set (generated by scripts/gen-invisible-charset.mjs, the same list the port
// reads from data/invisible-charset.json) closes that cross-layer gap. Consecutive
// code points collapse to `\u{a}-\u{b}` ranges so the class stays compact.
/** @param {readonly number[]} codepoints @returns {string} */
function cfClassSource(codepoints) {
  const sorted = [...codepoints].sort((a, b) => a - b);
  let src = "[";
  for (let i = 0; i < sorted.length;) {
    let j = i;
    while (j + 1 < sorted.length && sorted[j + 1] === sorted[j] + 1) j++;
    src += `\\u{${sorted[i].toString(16)}}`;
    if (j > i) src += `-\\u{${sorted[j].toString(16)}}`;
    i = j + 1;
  }
  return src + "]";
}

const CF_CLASS_SOURCE = cfClassSource(CF_CODEPOINTS);

// Stable, machine-readable category codes for the `found` array returned by
// stripInvisibleWithReport and sanitize. These are API: branch on them. They
// are deliberately NOT the human-facing prose (that lives in `warnings` and in
// CATEGORY_LABELS), so the display wording can be reworded without a breaking
// change to anyone matching on `found`.
export const CATEGORY = Object.freeze({
  CF: "cf-format",
  VARIATION_SELECTORS: "variation-selectors",
  BLANK_FILLERS: "blank-fillers",
  ANSI: "ansi",
  LONE_SURROGATES: "lone-surrogates",
  HTML_COMMENTS: "html-comments",
  HIDDEN_HTML: "hidden-html",
  EXFIL_URLS: "exfil-urls",
});

// code -> human label, used only to build `warnings` text. Decoupled from
// CATEGORY so prose changes never alter the machine-readable `found` contract.
/** @type {Readonly<Record<string, string>>} */
export const CATEGORY_LABELS = Object.freeze({
  [CATEGORY.CF]: "Format chars (Cf)",
  [CATEGORY.VARIATION_SELECTORS]: "Variation selectors",
  [CATEGORY.BLANK_FILLERS]: "Blank-rendering fillers",
  [CATEGORY.ANSI]: "ANSI escapes",
  [CATEGORY.LONE_SURROGATES]: "Lone UTF-16 surrogates",
  [CATEGORY.HTML_COMMENTS]: "HTML comments",
  [CATEGORY.HIDDEN_HTML]: "hidden HTML",
  [CATEGORY.EXFIL_URLS]: "exfil URLs",
});

/** @type {Array<[string, RegExp]>} Each entry pairs a CATEGORY code with its detector. */
export const CHECKS = [
  [CATEGORY.CF, new RegExp(CF_CLASS_SOURCE, REGEX_FLAGS)],
  [CATEGORY.VARIATION_SELECTORS, new RegExp(`[${VS}]`, REGEX_FLAGS)],
  // BLANK_NON_CF includes zero-width COMBINING marks (Mn: U+034F/17B4/17B5). In
  // a `u`-flag class each matches its own single code point — exactly the intent
  // (we strip the lone mark, never a base+mark grapheme), so the
  // misleading-character-class heuristic is a false positive here.
  // eslint-disable-next-line no-misleading-character-class -- single-code-point matches under the u flag are intentional
  [CATEGORY.BLANK_FILLERS, new RegExp(`[${BLANK_NON_CF}]`, REGEX_FLAGS)],
];

export const STRIP = new RegExp(
  CHECKS.map(([, regex]) => regex.source).join("|"),
  REGEX_FLAGS,
);

// SGR (Select Graphic Rendition) colour matching. Re-exported from ./ansi.mjs —
// the ONE ANSI grammar, shared with the Layer-1 stripper, which cannot import
// this module (layer1.mjs imports invisible.mjs, not the other way round). The
// two used to be separate regexes with DIFFERENT parameter rules, and the looser
// copy lived here: `ESC[12345m` read as SGR-only (so the operator got a
// "display-only colour" note) while the stripper could not match it and spliced
// a visible `[12345m` into the model's view.
export { SGR_RE } from "./ansi.mjs";

/**
 * True when every ANSI control introducer in `text` belongs to a display-only
 * SGR color sequence (so stripping the ANSI removes only cosmetic styling,
 * nothing that could move the cursor, erase, or carry a payload). Recognizes
 * both the 7-bit `ESC[…m` and 8-bit C1 (`U+009B…m`) SGR encodings.
 *
 * Answered by the STRIPPER'S OWN tokenizer: scanAnsi emits one token per raw
 * introducer — 7-bit ESC and the whole C1 block, so a C1 cursor-move
 * (`U+009B 2J`), a C1-OSC string (`U+009D … BEL`), a C1-DCS/APC payload and a
 * lone or partial escape each yield a non-SGR token — and the predicate is
 * "every token is SGR". Because the same scan decides what Layer 1 splices,
 * this can no longer report "colour only" for bytes the stripper leaves behind.
 * @param {string} text
 * @returns {boolean}
 */
export function isSgrOnly(text) {
  return scanAnsi(text).every((token) => token.kind === TOKEN_KIND.SGR);
}

export const LONG_RUN_THRESHOLD = 10;

/** Total invisible-char count above which a file/prompt is treated as
 * payload-capable even without a long run (threshold-evasion catch). */
export const SCATTERED_THRESHOLD = 30;

/**
 * The long-run pattern, declaratively: {@link LONG_RUN_THRESHOLD} or more
 * consecutive {@link STRIP} code points.
 *
 * Scan a document with {@link findLongRuns}, not with this: `exec`/`test`
 * throw `RangeError: Maximum call stack size exceeded` once a run passes
 * ~8.4 M code points, because V8 pushes one backtrack entry per iteration of
 * an unbounded quantifier onto a stack capped at 64 MB. This stays public as
 * the pattern itself, and as the independent oracle the scan is differenced
 * against (test/invisible-fast-path.test.mjs).
 */
export const LONG_RUN_RE = new RegExp(
  `(?:${STRIP.source}){${LONG_RUN_THRESHOLD},}`,
  REGEX_FLAGS,
);

// Iterations per `exec` below, which is what bounds the backtrack stack each
// one needs: a match can push at most this many entries, ~8x under the ceiling
// an unbounded quantifier walks into on an 8 MB payload. Runs longer than this
// are stitched from consecutive matches, so the bound costs an extra `exec`
// per megabyte of PAYLOAD and nothing at all on ordinary text.
const RUN_CHUNK = 1 << 20;

const LONG_RUN_CHUNK_RE = new RegExp(
  `(?:${STRIP.source}){${LONG_RUN_THRESHOLD},${RUN_CHUNK}}`,
  REGEX_FLAGS,
);

// The same class, sticky and from one repetition, to carry a run past the chunk
// bound: anchored at the end of the previous match, it either extends the run
// or fails immediately.
const RUN_TAIL_RE = new RegExp(`(?:${STRIP.source}){1,${RUN_CHUNK}}`, "yu");

/**
 * Every maximal run of at least {@link LONG_RUN_THRESHOLD} consecutive
 * payload-capable invisible code points in `text`, in order: `index` is the
 * run's UTF-16 offset, `text` its verbatim slice, `charCount` its length in
 * code points.
 *
 * What {@link LONG_RUN_RE} means, in the form every scanner in this package
 * uses — because that regex cannot answer for a large document, and an 8 MB
 * paste of zero-widths (the exact payload the scan exists to catch) is what
 * took out the SessionStart scanner, the prompt gate and the tool-output tier
 * alike. Bounding the quantifier bounds the backtrack stack per `exec`; a run
 * that hits the bound is continued by {@link RUN_TAIL_RE} until it ends, so the
 * runs reported are maximal at any length.
 * @param {string} text
 * @returns {Generator<{ index: number, text: string, charCount: number }>}
 */
export function* findLongRuns(text) {
  // Both regexes are module-level and carry `lastIndex`, and a generator can be
  // suspended anywhere — including inside another scan of another text. Every
  // exec below therefore sets its own start position first, so no scan can
  // inherit a position from one it interleaved with.
  let pos = 0;
  for (;;) {
    LONG_RUN_CHUNK_RE.lastIndex = pos;
    const match = LONG_RUN_CHUNK_RE.exec(text);
    if (match === null) return;
    let end = LONG_RUN_CHUNK_RE.lastIndex;
    // A run shorter than the bound fails this on the first try, for the cost of
    // one anchored no-match.
    for (;;) {
      RUN_TAIL_RE.lastIndex = end;
      if (RUN_TAIL_RE.exec(text) === null) break;
      end = RUN_TAIL_RE.lastIndex;
    }
    const run = text.slice(match.index, end);
    yield { index: match.index, text: run, charCount: codePointLength(run) };
    pos = end;
  }
}

/**
 * True when `text` carries at least one {@link findLongRuns} run.
 *
 * The bounded pattern answers this on its own: a run long enough to be reported
 * is long enough to match, whether or not the match reaches the run's end — so
 * the yes/no costs one anchored scan and never measures the run.
 * @param {string} text
 * @returns {boolean}
 */
export function hasLongRun(text) {
  LONG_RUN_CHUNK_RE.lastIndex = 0;
  return LONG_RUN_CHUNK_RE.test(text);
}

/**
 * The agent-facing "Stripped: …" note for a Layer-1 strip: the removed category
 * labels, the LONG RUN marker when the de-ANSI'd text still holds a
 * payload-length invisible run, and a pointer to recover the bytes — a hex dump
 * is ASCII, so it passes through sanitization untouched. The single source of
 * this note, shared by the `sanitize` convenience entry and the tool-output
 * pipeline so the two can't drift.
 * @param {string[]} invisFound CATEGORY codes applyLayer1 reported removing
 * @param {string} deAnsi ANSI-stripped text (invisible runs intact), for the LONG_RUN probe
 * @returns {string}
 */
export function describeStripped(invisFound, deAnsi) {
  let msg = `Stripped: ${invisFound.map((code) => CATEGORY_LABELS[code]).join(", ")}`;
  if (payloadLongRunSample(deAnsi) !== null)
    msg += " [LONG RUN — possible injection payload]";
  return (
    msg +
    " — inspect the removed bytes with a hex dump (xxd / od -c), which survives sanitization"
  );
}

// Leading-BOM marker, preserved by stripInvisibleWithReport (see its doc).
const BOM = "\uFEFF";
// ─── ZWNJ/ZWJ linguistic carve-out ───────────────────────────────────────────
// ZWNJ (U+200C) and ZWJ (U+200D) are general category Cf, so the STRIP pass
// would treat them as hidden-payload bytes. But they are MANDATORY for correct
// rendering between letters of several scripts (Arabic/Persian and many Indic
// scripts) and inside emoji ZWJ sequences — blanket stripping corrupts
// legitimate non-English output. Preserve them only where they do real
// rendering work, decided SYNTACTICALLY from the neighbours' Unicode
// Joining_Type (see isPreservedJoiner): a joiner between two cursive letters, an
// Indic joiner after a virama, an emoji joiner between emoji components. Strip
// them as payload everywhere else — leading/trailing, next to a non-joining
// character (ASCII, punctuation, a non-connecting letter), or inside a joiner
// run. Over-strip beats under-strip only on genuine ambiguity; a joiner sitting
// between two real cursive letters is treated as content and kept.
const ZWNJ = 0x200c;
const ZWJ = 0x200d;

// Max joiners the carve-out will PRESERVE within one uninterrupted joined
// cluster (a `letter (joiner letter)*` chain, or an emoji ZWJ sequence). A real
// word or emoji glyph needs only a handful in a row — the longest standard emoji
// ZWJ sequences (family-of-four, profession+ZWJ) carry three; a Persian
// compound a couple. Past this many consecutive PRESERVED joiners with no real
// gap between them, the chain is treated as a zero-width payload channel (an
// attacker alternates `letter joiner letter joiner …` so every joiner still sits
// between two cursive letters) and the surplus joiners are stripped. The counter
// resets at any genuine gap — two visible characters in a row, i.e. text that is
// NOT part of a joined cluster — so an ordinary single joiner per word is kept.
export const CONSECUTIVE_JOINER_CAP = 8;

// Max variation selectors the carve-out preserves in one uninterrupted run of
// selected glyphs (an `ideograph selector ideograph selector …` chain, or the
// standardized-variation equivalent). Each selector encodes up to a byte, so an
// attacker who variant-selects every character of a CJK/base run opens a
// high-bit-rate channel that the joiner cap does not touch (these are not
// joiners). A genuine document variant-selects only the odd rare glyph, never a
// long unbroken run, so past this many consecutive PRESERVED IVS/stdvs with no
// real gap the surplus is stripped. The counter resets at a genuine gap (two
// visible characters in a row), exactly like CONSECUTIVE_JOINER_CAP.
export const CONSECUTIVE_SELECTOR_CAP = 8;

// Floor on the document-wide preserve budget for joiners, selectors and tag
// sequences (see `kind` in analyzeCarve — blank fillers are NOT charged here;
// they have their own allowance, see TOTAL_PRESERVED_BLANK_BUDGET). The
// Joining_Type gate strips joiners that do no
// rendering work regardless of count, so the bulk covert channel (ZWNJ
// scattered through Latin/ASCII/mixed text) is closed by shape, not by
// counting. What remains is the residual channel of MEANINGFUL joiners/
// selectors stuffed into genuine cover text — each individually legitimate,
// so indistinguishable one at a time. THIS budget (with CONSECUTIVE_JOINER_CAP
// and SCATTERED_THRESHOLD) is the explicit, tunable bound on that residual
// channel; it is not derived, and tightening it trades covert-channel width for
// clipping genuinely dense prose or emoji-dense text. The allowance is
// proportional to visible length (PRESERVED_JOINER_PER_VISIBLE), never below
// this floor; the floor keeps short but joiner/selector-dense strings (a lone
// emoji ZWJ sequence, a two-word Persian phrase) un-flagged. Past the
// allowance the surplus is stripped AND reported.
export const TOTAL_PRESERVED_JOINER_BUDGET = 16;

// Visible code points required per additional preserved joiner above the floor.
// Measured formal/literary Persian runs ~1 ZWNJ per 5 words (~25 visible chars);
// 1-per-8 sits comfortably above real prose density while still bounding the
// residual channel to a fixed fraction of the cover text.
export const PRESERVED_JOINER_PER_VISIBLE = 8;

// Absolute ceiling on the document-wide preserve allowance, regardless of how
// much visible cover text an attacker supplies. Without it, maxPreserved grows
// linearly with visible length (visibleLen / PRESERVED_JOINER_PER_VISIBLE), so a
// large benign-looking body lets the residual joiner/selector channel scale with
// attacker input — preserved chars do not count toward the scatter floor, so
// nothing else bounds it. This caps the whole channel at a fixed width no cover
// text can widen.
export const PRESERVE_HARD_CAP = 64;

// Floor on the document-wide allowance for PRESERVED blank fillers (the
// Braille blank and the Hangul fillers — see the blank-filler carve-out). Kept
// separate from the joiner/selector budget because the two have completely
// different legitimate densities, and short blank-dense strings (a one-line
// Braille phrase, a lone archaic syllable) must stay un-clipped.
export const TOTAL_PRESERVED_BLANK_BUDGET = 16;

// Visible ANCHOR-script code points (a non-blank Braille cell, a non-filler
// Hangul jamo/syllable) required per preserved blank filler above the floor. A
// blank is only ever preservable next to one of these, so this ratio is what
// separates real text from the degenerate channel: U+2800 separates WORDS and a
// filler completes a syllable, so genuine text spends several anchor characters
// per blank and stays under one blank per two anchors, while the alternation an
// attacker needs to stuff a bit per character (`가ᅟ가ᅟ…`, `⠃⠀⠃⠀…`) is exactly
// 1:1 and fails.
//
// Deliberately NOT capped by PRESERVE_HARD_CAP: an absolute ceiling is what
// truncated long Braille documents, and unlike the joiner channel this one
// cannot scale on invisible cover text — every additional bit costs the
// attacker two VISIBLE anchor-script characters, and the blanks themselves
// render as spacing a reader can see. Over the ratio, NO blank in the document
// is preserved (all-or-nothing, so a document never comes out half-spaced) and
// every one of them becomes payload — which then also feeds the scatter floor.
export const PRESERVED_BLANK_PER_ANCHOR = 2;

// Scripts whose orthography uses ZWNJ/ZWJ between letters as a rendering
// control. The runtime gate is now script-agnostic (it reads Joining_Type, so it
// covers every cursive/Brahmic script, not just these), but this list remains
// the public, TESTED SSOT of the scripts the carve-out is designed for: the
// suite drives one preserve-case per entry, so a regression in any of them
// fails.
export const LINGUISTIC_SCRIPTS = [
  "Arabic",
  "Devanagari",
  "Bengali",
  "Gurmukhi",
  "Gujarati",
  "Oriya",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Sinhala",
];
// Left side of an emoji joiner: a pictograph or a skin-tone modifier (a base
// emoji may carry a modifier before the joiner, e.g. a health-worker sequence).
const EMOJI_LEFT = /[\p{Extended_Pictographic}\p{Emoji_Modifier}]/u;
// The three keycap bases (digit, `#`, `*`) Unicode's keycap grammar allows
// before VS16 + U+20E3 COMBINING ENCLOSING KEYCAP (1️⃣ #️⃣ *️⃣ … 9️⃣). None is
// Extended_Pictographic or Emoji_Modifier, so EMOJI_LEFT misses them; the
// presentation-selector check accepts one ONLY when the required U+20E3 keycap
// actually follows the selector (see isEmojiPresentationSelector). A bare
// digit/`#`/`*` + VS with no keycap is NOT a glyph — it is a hidden presentation
// selector spliced after ordinary text, the top low-effort VS-smuggling shape —
// so it fails closed and is stripped. The base set is confined to the keycap
// check (never folded into EMOJI_LEFT) so it cannot loosen the ZWJ carve-out.
const KEYCAP_BASE = /[0-9#*]/u;
// U+20E3 COMBINING ENCLOSING KEYCAP — the mandatory terminator of a keycap
// sequence, the one signal that a digit/`#`/`*` + VS16 is a real glyph.
const COMBINING_KEYCAP = 0x20e3;
// Right side of an emoji joiner is always the next component's base pictograph.
const EMOJI_BASE = /\p{Extended_Pictographic}/u;
// A variation selector legitimately sits between a base pictograph and a
// following ZWJ (🏳️‍🌈 = flag base, VS16, ZWJ, rainbow; 👁️‍🗨️), so the joiner's real
// left neighbor for the emoji test is the pictograph, not the selector.
const VARIATION_SELECTOR = new RegExp(`[${VS}]`, "u");
// Code-point twins of the four single-character classes above, memoized: the
// carve analysis asks these per invisible (and per neighbour), and a Unicode
// property class costs far more than a table hit. See memoizedCpPredicate.
const isEmojiLeft = memoizedCpPredicate(EMOJI_LEFT);
const isEmojiBase = memoizedCpPredicate(EMOJI_BASE);
const isKeycapBase = memoizedCpPredicate(KEYCAP_BASE);
const isVariationSelectorCp = memoizedCpPredicate(VARIATION_SELECTOR);
// U+FE0F (VS16) forces emoji presentation, U+FE0E (VS15) forces text
// presentation (☺︎ vs ☺); either one directly after a pictograph is part of a
// visible glyph, not a hidden variation-selector run.
const PRESENTATION_SELECTORS = new Set([0xfe0e, 0xfe0f]);

// ─── Emoji tag sequences (subregional flags) ─────────────────────────────────
// A subregional flag (🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland, 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales, 🏴󠁧󠁢󠁥󠁮󠁧󠁿 England …) is a WAVING
// BLACK FLAG tag_base (U+1F3F4, a visible pictograph) followed by one or more
// tag characters in U+E0020–U+E007E, terminated by U+E007F CANCEL TAG. Only that
// exact grammar is preserved verbatim; any tag char (the whole U+E0000–U+E007F
// block is category Cf) NOT inside a well-formed 🏴 … CANCEL run stays stripped —
// tag chars are the top ASCII-smuggling vector, so preservation fails CLOSED on a
// malformed/partial run.
const TAG_BASE = 0x1f3f4; // WAVING BLACK FLAG
const TAG_CANCEL = 0xe007f; // CANCEL TAG (the required terminator)
const TAG_SPEC_MIN = 0xe0020; // first tag char a flag sequence may carry
const TAG_SPEC_MAX = 0xe007e; // last tag char a flag sequence may carry
// A tag char decodes to ASCII (cp − 0xE0000), so a grammatically-valid
// 🏴 … CANCEL run can spell ARBITRARY ASCII ("ignore rules") and, if preserved
// only on grammar, smuggle it verbatim to the model. Preservation is therefore
// gated on the decoded payload naming a REGISTERED subdivision (the only tag
// sequences that render as a real flag) and on a tag-char cap — every other
// run, however well-formed, stays stripped (fail closed on the top ASCII vector).
const REGISTERED_TAG_PAYLOADS = new Set(["gbeng", "gbsct", "gbwls"]);
// Longest registered subdivision payload is 5 tag chars; cap a touch above it so
// a malformed-but-registered-prefix run can never carry a long ASCII rider.
const MAX_TAG_SPEC_CHARS = 6;

// ─── Ideographic variation selectors (VS17–VS256, U+E0100–U+E01EF) ────────────
// An ideographic variation sequence is a CJK ideograph followed by a selector in
// U+E0100–U+E01EF. Preserved ONLY when the immediately preceding code point is a
// CJK ideograph — the registry-faithful structural gate (IVS apply to ideographs
// and nothing else).
//
// Derived from Unicode's own data rather than hand-transcribed block spans: the
// Unified_Ideograph property IS the set of unified ideographs (URO + every
// extension), versioned with the runtime's ICU, so a new extension arrives with
// the Node upgrade instead of waiting for someone to notice. A hand-written
// table went stale exactly this way — it stopped at Extension H and so denied
// the 4,298 Extension J ideographs (U+323B0–U+33479) a legitimate IVS base.
//
// Script=Han is deliberately NOT used: it also covers radicals (U+2E80–U+2EF3),
// Kangxi radicals, U+3005/U+3007 and the ideographic-description characters,
// none of which is an IVS base. Script_Extensions=Han is wider still (it reaches
// U+00B7 MIDDLE DOT and the CJK punctuation shared with Kana), so it would let a
// full stop anchor a variation selector.
//
// The two Compatibility Ideograph BLOCKS stay literal: they are not
// Unified_Ideograph, and JS RegExp exposes no \p{Block=…}. Block boundaries are
// immutable by Unicode's stability policy, so a literal span cannot drift; the
// contract test in test/invisible-unicode-tables.test.mjs pins that every
// ASSIGNED code point inside them is a Script=Han letter.
const IVS_MIN = 0xe0100;
const IVS_MAX = 0xe01ef;
const CJK_IDEOGRAPH_RE =
  /[\p{Unified_Ideograph}\u{F900}-\u{FAFF}\u{2F800}-\u{2FA1F}]/u;

/** True when `cp` is a CJK ideograph (the only base an ideographic variation
 * selector legitimately follows). -1 (past a string boundary) is not.
 * @type {(cp: number) => boolean} */
const isCjkIdeograph = memoizedCpPredicate(CJK_IDEOGRAPH_RE);

// Brahmic consonants: the only base a virama does half-form/conjunct work on.
// A bare or base-less halant + ZWJ carries no rendering and is a smuggling
// channel, so the Indic joiner is preserved only over one of these.
//
// The spans are GENERATED from the UCD (Indic_Syllabic_Category=Consonant,
// restricted by Script) and live in ./joining-type.mjs alongside the virama
// table they are read against — see scripts/gen-joining-type.mjs. They used to
// be hand-typed per-block KA–HA approximations here, which swept up the holes
// between the real consonants; ECMAScript exposes no
// \p{Indic_Syllabic_Category=…} escape, and \p{Script=Devanagari} is the wrong
// shape on its own (it also holds the independent vowels U+0904–U+0914, which a
// virama never attaches to), so a generated table is the only drift-proof
// answer. Re-exported here because it was part of this module's surface before
// it moved, and because test/invisible-unicode-tables.test.mjs checks each span
// against the script it claims.
export { BRAHMIC_CONSONANT_RANGES } from "./joining-type.mjs";

/** True when the code point `cp` is a Brahmic consonant; -1 (past a string
 * boundary) is not. A thin sign-guard over ./joining-type.mjs's table lookup.
 * @param {number} cp @returns {boolean} */
function isBrahmicConsonantCp(cp) {
  return cp >= 0 && isBrahmicConsonant(cp);
}

// ─── Blank-filler carve-out (Braille / archaic Hangul) ───────────────────────
// U+2800 (BRAILLE PATTERN BLANK) and the Hangul fillers render blank, so a RUN
// of them is a hidden channel — but a lone one does real work in genuine Braille
// (the empty cell) or archaic-Korean text, where stripping it mangles content.
// Gate them like the joiner carve-out: preserve one only next to a real,
// script-appropriate visible neighbour (a non-blank Braille cell; a Hangul
// jamo/syllable). A run of fillers has only fillers for neighbours, so it fails
// the anchor and is stripped — the run-length gate falls out of the anchor. The
// zero-width Mn marks in BLANK_NON_CF (U+034F/17B4/17B5) have no such benign
// standalone use, so they are never preserved.
//
// Blank fillers are NOT charged against the joiner/selector preserve budget:
// that budget's density model is "~1 preserved invisible per 8 visible chars"
// (PRESERVED_JOINER_PER_VISIBLE), measured on Persian ZWNJ prose, with a fixed
// PRESERVE_HARD_CAP ceiling. Blanks are an order of magnitude denser in genuine
// text — U+2800 IS the word space of Unicode Braille, and a Hangul filler
// completes a defective syllable — so charging them there mangled real content:
// a 40-word Braille passage lost 14 of its 39 word spaces (words run together)
// and a 200-word one kept 64 of 199, with `found` reporting a strip on a
// perfectly legitimate document. They draw on the anchor-proportional allowance
// below instead (see TOTAL_PRESERVED_BLANK_BUDGET).
const BRAILLE_BLANK = 0x2800;
const HANGUL_FILLERS = new Set([0x115f, 0x1160, 0x3164, 0xffa0]);
// Code points that trigger the carve-out path for blank fillers (see
// needsCarveOut). Written as \u escapes: a raw blank-rendering byte in a regex
// literal is invisible to the eye and a correctness landmine for the next editor.
const GATED_BLANK_RE = new RegExp("[\\u115F\\u1160\\u2800\\u3164\\uFFA0]", "u");

// Script=Braille, from the runtime's Unicode data (identical to
// Script_Extensions=Braille — no character is shared with another script).
const BRAILLE_RE = /\p{Script=Braille}/u;

const isBrailleScript = memoizedCpPredicate(BRAILLE_RE);

/** A real (non-blank) Braille cell — the anchoring neighbour for a U+2800 blank.
 * @param {number} cp @returns {boolean} */
function isBrailleCell(cp) {
  return cp !== BRAILLE_BLANK && isBrailleScript(cp);
}

// Script=Hangul, straight from the runtime's Unicode data. NOT
// Script_Extensions=Hangul: that set also holds the CJK punctuation Korean text
// shares with Chinese and Japanese (U+3001 IDEOGRAPHIC COMMA, U+30FB KATAKANA
// MIDDLE DOT, U+FF61–U+FF65 …), so a Japanese middle dot would anchor — and
// thereby preserve — a Hangul filler in text with no Hangul in it at all.
const HANGUL_RE = /\p{Script=Hangul}/u;

const isHangulScript = memoizedCpPredicate(HANGUL_RE);

/** A Hangul jamo/syllable (NOT itself one of the fillers) — the anchoring
 * neighbour for a Hangul filler. @param {number} cp @returns {boolean} */
function isHangul(cp) {
  if (HANGUL_FILLERS.has(cp)) return false; // a filler cannot anchor another filler
  return isHangulScript(cp);
}

// The carve analysis runs once per code point of every prompt and every tool
// output, so its per-code-point state is held in TYPED arrays of small integer
// codes rather than arrays of category strings: `Uint8Array` costs one byte per
// code point with no pointer to trace, where a `(string|null)[]` costs a machine
// word per entry and hands the collector one more object graph to walk on every
// blocking hook call. These are the codes; CODE_CATEGORY projects them back onto
// the public CATEGORY strings at the boundary, so nothing outside this module
// sees them.
const CODE_VISIBLE = 0;
const CODE_CF = 1;
const CODE_VS = 2;
const CODE_BLANK = 3;

// Preserve kinds, in the same one-byte-per-code-point spirit. KIND_NONE is the
// zero value, so a freshly allocated `kind` array already reads "payload" —
// which is the fail-closed default this analysis wants.
const KIND_NONE = 0;
const KIND_JOINER = 1;
const KIND_EMOJIVS = 2;
const KIND_TAG = 3;
const KIND_STDVS = 4;
const KIND_IVS = 5;
const KIND_BLANK = 6;

/** Small code -> CHECKS category, indexed by the CODE_* values above. In CHECKS
 * order, so a code point in two sets reports the category the regexes would
 * report first. @type {(string|null)[]} */
const CODE_CATEGORY = [
  null,
  CATEGORY.CF,
  CATEGORY.VARIATION_SELECTORS,
  CATEGORY.BLANK_FILLERS,
];

// code point -> CODE_* above, projected from the SAME three code-point sets the
// CHECKS regexes are built from, in CHECKS order. Every CHECKS class holds
// single code points under the `u` flag, so a lookup and a `.test` answer
// identically; test/invisible-fast-path.test.mjs pins that over the whole
// code-point space, because a code point dropped here is one the scatter gate
// stops counting.
/** @type {Map<number, number>} */
const TRACKED_INVISIBLE = new Map();
for (const [code, codepoints] of /** @type {[number, Iterable<number>][]} */ ([
  [CODE_CF, CF_CODEPOINTS],
  [CODE_VS, [...VS].map((ch) => ch.codePointAt(0))],
  [CODE_BLANK, [...BLANK_NON_CF].map((ch) => ch.codePointAt(0))],
]))
  for (const cp of codepoints)
    if (!TRACKED_INVISIBLE.has(cp)) TRACKED_INVISIBLE.set(cp, code);

// No tracked code point sits below this, so ASCII and Latin-1 text answers the
// classifier without touching the map at all.
const MIN_TRACKED_CP = Math.min(...TRACKED_INVISIBLE.keys());

/**
 * The CODE_* class a code point belongs to, or CODE_VISIBLE when it is not
 * payload-capable (an ordinary visible character).
 * @param {number} cp
 * @returns {number}
 */
function classifyCp(cp) {
  if (cp < MIN_TRACKED_CP) return CODE_VISIBLE;
  return TRACKED_INVISIBLE.get(cp) ?? CODE_VISIBLE;
}

// Distinct code points a memoizedCpPredicate will remember. Comfortably above
// the character repertoire of any real document (and of every test corpus here)
// while bounding what a single hostile paste can make one predicate retain.
const CP_PREDICATE_MEMO_CAP = 4096;

/**
 * A code-point predicate backed by a single-code-point RegExp, memoized on the
 * code point.
 *
 * The carve analysis asks these of the same handful of code points over and
 * over — a document is a few hundred distinct characters repeated — and each
 * ask otherwise costs a `String.fromCodePoint` allocation plus a Unicode
 * property-class match. The memo is a pure accelerator: it answers exactly what
 * the RegExp answers, for the same input, forever (a code point's Unicode
 * properties do not change inside a process).
 *
 * The entry cap is a MEMORY policy, not a scan bound: past it the predicate
 * still answers every code point, just without recording new ones, so no input
 * can change a verdict by overflowing the table — only by giving up the speed-up
 * it would otherwise have had.
 * @param {RegExp} re  single-code-point matcher
 * @returns {(cp: number) => boolean}
 */
function memoizedCpPredicate(re) {
  /** @type {Map<number, boolean>} */
  const memo = new Map();
  return (cp) => {
    if (cp < 0) return false; // past a string boundary: the "" neighbour
    const hit = memo.get(cp);
    if (hit !== undefined) return hit;
    const answer = re.test(String.fromCodePoint(cp));
    if (memo.size < CP_PREDICATE_MEMO_CAP) memo.set(cp, answer);
    return answer;
  };
}

/**
 * `text` as its code points, in the units the String iterator yields — the same
 * sequence `Array.from(text)` produces (an unpaired surrogate stands alone as
 * itself), as numbers rather than one heap-allocated one-character string each.
 * Every carve-analysis predicate reads a code point, so the numbers are the
 * whole requirement: a 256 KB paste that would cost a quarter of a million
 * short-lived strings per pass costs one buffer, and the collector stays out of
 * a blocking hook.
 * @param {string} text
 * @returns {Int32Array}
 */
function codePointArray(text) {
  const cps = new Int32Array(text.length);
  let n = 0;
  for (let i = 0; i < text.length; i++) {
    const unit = text.charCodeAt(i);
    let cp = unit;
    if (unit >= 0xd800 && unit <= 0xdbff && i + 1 < text.length) {
      const low = text.charCodeAt(i + 1);
      if (low >= 0xdc00 && low <= 0xdfff) {
        cp = (unit - 0xd800) * 0x400 + (low - 0xdc00) + 0x10000;
        i++;
      }
    }
    cps[n++] = cp;
  }
  return n === cps.length ? cps : cps.subarray(0, n);
}

/**
 * True when `text` holds at least one code point {@link classifyCp} calls
 * invisible. Walks UTF-16 units directly rather than building the code-point
 * array, so a clean multi-MB paste is answered without allocating anything;
 * surrogates are paired exactly as the String iterator pairs them, an unpaired
 * one classifying as the lone surrogate it is.
 * @param {string} text
 * @returns {boolean}
 */
function hasInvisibleCodePoint(text) {
  for (let i = 0; i < text.length; i++) {
    let cp = text.charCodeAt(i);
    if (cp >= 0xd800 && cp <= 0xdbff && i + 1 < text.length) {
      const low = text.charCodeAt(i + 1);
      if (low >= 0xdc00 && low <= 0xdfff) {
        cp = (cp - 0xd800) * 0x400 + (low - 0xdc00) + 0x10000;
        i++;
      }
    }
    if (classifyCp(cp) !== CODE_VISIBLE) return true;
  }
  return false;
}

/**
 * The number of code points in `text`, counted by the String iterator itself —
 * the same unit `Array.from(text).length` measures, without the array.
 * @param {string} text
 * @returns {number}
 */
function codePointLength(text) {
  let n = 0;
  const iterator = text[Symbol.iterator]();
  while (!iterator.next().done) n++;
  return n;
}

/** A cursive-joining letter: Joining_Type dual, right, or left. (C is a join
 * control, T is a transparent mark, U is non-joining — none is a letter that a
 * ZWNJ/ZWJ does rendering work between.)
 * @param {string} jt @returns {boolean} */
const isCursiveLetter = (jt) => jt === "D" || jt === "R" || jt === "L";

/** The Joining_Type of a code point, or "U" for -1 (past a string boundary).
 * @param {number} cp @returns {string} */
const jtOf = (cp) => (cp < 0 ? "U" : joiningType(cp));

/** True when `cp` is itself a ZWNJ/ZWJ (used to reject joiner runs).
 * @param {number} cp @returns {boolean} */
function isJoinControl(cp) {
  return cp === ZWNJ || cp === ZWJ;
}

/**
 * The nearest neighbour of index `i` in direction `dir`, skipping Transparent
 * (combining-mark) code points, as the Unicode cursive-joining algorithm does —
 * a harakat between a letter and a ZWNJ does not break the join. Also skips any
 * OTHER tracked invisible that is itself removable (blank fillers, format
 * chars): it does no cursive-shaping work and gets stripped, so a joiner's real
 * neighbour is the next surviving character. Without this a payload byte wedged
 * between two joiners hides the joiner-RUN until a first pass removes it, after
 * which a second pass strips the now-adjacent joiners — non-idempotent. Join
 * controls (ZWNJ/ZWJ) are deliberately NOT skipped: they are the run signal.
 * Returns -1 past the string boundary (the old "" neighbour).
 * @param {Int32Array} cps @param {number} i @param {number} dir  -1 or +1
 * @returns {number}
 */
function effectiveNeighbor(cps, i, dir) {
  for (let j = i + dir; j >= 0 && j < cps.length; j += dir) {
    const cp = cps[j];
    if (jtOf(cp) === "T") continue;
    if (!isJoinControl(cp) && classifyCp(cp) !== CODE_VISIBLE) continue;
    return cp;
  }
  return -1;
}

/**
 * True when the joiner at `cps[i]` follows a virama that itself sits on a real
 * Brahmic consonant — a genuine half-form/conjunct request (क् + ZWJ), not a
 * bare or base-less halant (a smuggling channel a raw `cps[i-1]` virama test
 * would wave through). Steps left over removable invisibles to LAND on the
 * virama (which is Joining_Type Transparent, so it is the anchor, never skipped),
 * then uses effectiveNeighbor to find the consonant base past any transparent
 * marks / invisibles between it and the virama.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function followsBrahmicConjunct(cps, i) {
  let j = i - 1;
  while (
    j >= 0 &&
    !isJoinControl(cps[j]) &&
    classifyCp(cps[j]) !== CODE_VISIBLE
  )
    j--;
  if (j < 0 || !isVirama(cps[j])) return false;
  return isBrahmicConsonantCp(effectiveNeighbor(cps, j, -1));
}

/**
 * True when the joiner at `cps[i]` does real rendering work and so must be
 * preserved rather than stripped, decided from the neighbours' Joining_Type:
 *   - emoji ZWJ: between two emoji components (its left pictograph may sit behind
 *     a VS16, so step over selectors — see leftNonSelector);
 *   - Indic joiner: after a virama that sits on a real Brahmic consonant;
 *   - Arabic-family joiner: between two cursive letters (ZWNJ needs both, ZWJ at
 *     least one — it forces a connected form). A joiner whose effective neighbour
 *     is ANOTHER joiner is a run (a zero-width payload channel) and is rejected.
 * Leading/trailing joiners fall out because the -1 boundary has Joining_Type U.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function isPreservedJoiner(cps, i) {
  const cp = cps[i];
  if (cp !== ZWNJ && cp !== ZWJ) return false;
  // Emoji ZWJ sequences use ZWJ only; the real neighbours are the pictographs,
  // which may each sit behind a variation selector (🏳️‍🌈 = base VS16 ZWJ rainbow;
  // a selector can also follow the ZWJ before the next base), so step over
  // selectors on BOTH sides — leftNonSelector and its mirror rightNonSelector.
  if (
    cp === ZWJ &&
    isEmojiLeft(leftNonSelector(cps, i)) &&
    isEmojiBase(rightNonSelector(cps, i))
  )
    return true;
  // Indic: meaningful only after a virama sitting on a real consonant base.
  if (followsBrahmicConjunct(cps, i)) return true;
  // Arabic-family cursive joining, on the nearest non-Transparent neighbours.
  const left = effectiveNeighbor(cps, i, -1);
  const right = effectiveNeighbor(cps, i, 1);
  if (isJoinControl(left) || isJoinControl(right)) return false; // joiner run
  const lc = isCursiveLetter(jtOf(left));
  const rc = isCursiveLetter(jtOf(right));
  return cp === ZWNJ ? lc && rc : lc || rc;
}

/**
 * True when `cps[i]` is a presentation selector (VS15 U+FE0E or VS16 U+FE0F)
 * that is part of a visible glyph, not a hidden VS run:
 *   - directly after a pictograph/skin-tone modifier, preserved; OR
 *   - directly after a keycap base (digit/`#`/`*`) AND immediately followed by
 *     U+20E3 COMBINING ENCLOSING KEYCAP — a complete keycap glyph (1️⃣ #️⃣ …).
 * A keycap base + selector with NO trailing U+20E3 is a bare hidden presentation
 * selector, so it fails closed and is stripped. A longer selector run still
 * surfaces: the next selector's left neighbour is itself a selector.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function isEmojiPresentationSelector(cps, i) {
  if (!PRESENTATION_SELECTORS.has(cps[i])) return false;
  const prev = i > 0 ? cps[i - 1] : -1;
  if (isEmojiLeft(prev)) return true;
  return (
    isKeycapBase(prev) &&
    (i + 1 < cps.length ? cps[i + 1] : -1) === COMBINING_KEYCAP
  );
}

/**
 * Per-invisible carve-out analysis, shared by carveStrip and
 * countPayloadInvisible: for each code point, its CODE_* class (CODE_VISIBLE
 * when visible) and its preserve KIND_* (KIND_NONE when the char is payload).
 * Everything invisible that is NOT preserve-eligible is payload; the scatter
 * floor counts only that, so meaningful joiners/selectors never push honest
 * prose over the threshold.
 * @param {Int32Array} cps
 * @returns {{ codes: Uint8Array, kind: Uint8Array, payloadInvis: number, visibleLen: number }}
 */
function analyzeCarve(cps) {
  const codes = new Uint8Array(cps.length);
  // Indices of the invisibles, so every pass below is O(invisibles) rather than
  // O(length): in ordinary text they are a vanishing fraction of a paste, and a
  // full-length pass per preserve rule is what made the analysis linear in the
  // WHOLE prompt several times over.
  let invisCount = 0;
  let visibleLen = 0;
  let hasTagBase = false;
  for (let i = 0; i < cps.length; i++) {
    const code = classifyCp(cps[i]);
    codes[i] = code;
    if (code !== CODE_VISIBLE) {
      invisCount++;
      continue;
    }
    visibleLen++;
    hasTagBase ||= cps[i] === TAG_BASE;
  }
  // Sized exactly, from the count the pass above already produced: a growable
  // array reallocates its way up through a document that is mostly invisible,
  // and that churn is the collector's whole share of this function.
  const invisible = new Int32Array(invisCount);
  for (let i = 0, at = 0; at < invisCount; i++)
    if (codes[i] !== CODE_VISIBLE) invisible[at++] = i;
  // A tag sequence is preservable only when it opens on a TAG_BASE pictograph,
  // so with no base in the text markTagSequences returns all-false.
  const tagKeep = hasTagBase ? markTagSequences(cps) : null;
  const kind = new Uint8Array(cps.length);
  for (const i of invisible) {
    if (tagKeep !== null && tagKeep[i]) kind[i] = KIND_TAG;
    else if (isPreservedJoiner(cps, i)) kind[i] = KIND_JOINER;
    else if (isEmojiPresentationSelector(cps, i)) kind[i] = KIND_EMOJIVS;
    else if (isStandardizedVariationSelector(cps, i)) kind[i] = KIND_STDVS;
    else if (isIdeographicVariationSelector(cps, i)) kind[i] = KIND_IVS;
    else if (isPreservedBlankFiller(cps, i)) kind[i] = KIND_BLANK;
  }
  // Blank fillers are budgeted here, document-wide and all-or-nothing, against
  // the visible anchor-script text rather than against the joiner/selector
  // counter in carveStrip (see PRESERVED_BLANK_PER_ANCHOR for why the two
  // cannot share a density model). Deciding it in analyzeCarve rather than in
  // the emit loop keeps countPayloadInvisible and payloadInvisibleView honest:
  // a blank the stripper will remove is payload to every consumer, so the
  // prompt layer's scatter gate sees it without re-deriving the budget.
  //
  // Budgeted PER SCRIPT, because a blank never anchors cross-script: pooling the
  // two anchor counts would let one script's cover text fund the other's
  // channel, so 400 chars of ordinary Korean prose would buy an unreported
  // `⠃⠀⠃⠀…` alternation of 200 Braille blanks. The anchor scan is skipped below
  // the floor: it costs a script regex per visible character, and analyzeCarve
  // runs on every prompt and tool output.
  /** @type {Record<string, number[]>} */
  const blankIndices = { braille: [], hangul: [] };
  for (const i of invisible)
    if (kind[i] === KIND_BLANK)
      blankIndices[cps[i] === BRAILLE_BLANK ? "braille" : "hangul"].push(i);
  for (const [
    script,
    isAnchor,
  ] of /** @type {[string, (cp: number) => boolean][]} */ ([
    ["braille", isBrailleCell],
    ["hangul", isHangul],
  ])) {
    const indices = blankIndices[script];
    if (indices.length <= TOTAL_PRESERVED_BLANK_BUDGET) continue;
    let anchors = 0;
    for (let i = 0; i < cps.length; i++)
      if (codes[i] === CODE_VISIBLE && isAnchor(cps[i])) anchors++;
    if (indices.length > Math.floor(anchors / PRESERVED_BLANK_PER_ANCHOR))
      for (const i of indices) kind[i] = KIND_NONE;
  }
  let payloadInvis = 0;
  for (const i of invisible) if (kind[i] === KIND_NONE) payloadInvis++;
  return { codes, kind, payloadInvis, visibleLen };
}

/**
 * Count the PAYLOAD invisible code points in `text`: those the carve-out would
 * strip, excluding ZWNJ/ZWJ (and emoji VS16) that do real rendering work.
 * Consumers that gate on invisible density (e.g. the prompt classifier's scatter
 * threshold) use this so legitimate dense multilingual prose is not mistaken for
 * a hidden channel.
 * @param {string} text
 * @returns {number}
 */
export function countPayloadInvisible(text) {
  // Payload is a SUBSET of the invisibles (analyzeCarve counts only positions
  // classifyCp marks invisible), so a text with none has a payload count of zero
  // and needs neither the code-point array nor the carve analysis. This reads
  // every code point — it is a necessary condition checked in full, not a scan
  // bound an attacker could paste past.
  if (!hasInvisibleCodePoint(text)) return 0;
  return analyzeCarve(codePointArray(text)).payloadInvis;
}

/**
 * Bulk strip (the common path: {@link needsCarveOut} found nothing the
 * carve-out could apply to). A single regex pass removes every payload-
 * capable char; `found` names the category codes present via `.search`
 * (which ignores the `g` lastIndex).
 * @param {string} body
 * @returns {{ cleaned: string, found: string[] }}
 */
function bulkStrip(body) {
  const found = CHECKS.filter(([, re]) => body.search(re) !== -1).map(
    ([code]) => code,
  );
  return { cleaned: body.replace(STRIP, ""), found };
}

/**
 * The nearest code point left of index `i` that is not a variation selector, or
 * -1 at the string start. An emoji ZWJ sequence can place a VS16 between the base
 * pictograph and the ZWJ, so the joiner's real left neighbor is found by stepping
 * over any variation selector(s).
 * @param {Int32Array} cps
 * @param {number} i
 * @returns {number}
 */
function leftNonSelector(cps, i) {
  let p = i - 1;
  while (p >= 0 && isVariationSelectorCp(cps[p])) p--;
  return p >= 0 ? cps[p] : -1;
}

/**
 * The nearest code point right of index `i` that is not a variation selector, or
 * -1 at the string end. Mirror of {@link leftNonSelector}: an emoji ZWJ can be
 * followed by a selector before the next component's base pictograph, so the
 * joiner's real right neighbor is found by stepping over any variation
 * selector(s).
 * @param {Int32Array} cps
 * @param {number} i
 * @returns {number}
 */
function rightNonSelector(cps, i) {
  let p = i + 1;
  while (p < cps.length && isVariationSelectorCp(cps[p])) p++;
  return p < cps.length ? cps[p] : -1;
}

/**
 * Mark every index that belongs to a PRESERVABLE emoji tag sequence (subregional
 * flag): a U+1F3F4 tag_base, then tag chars in U+E0020–U+E007E whose decoded
 * ASCII payload names a REGISTERED subdivision, then U+E007F CANCEL TAG. Only the
 * tag chars and the terminating CANCEL are marked (the base is a visible
 * pictograph). A run missing the CANCEL, exceeding the tag-char cap, or whose
 * payload is not a registered subdivision is left unmarked so it is stripped —
 * grammatical validity alone is NOT enough, since a valid run spells arbitrary
 * ASCII (fail closed on the top ASCII-smuggling vector).
 * @param {Int32Array} cps
 * @returns {Uint8Array} keep[i] non-zero iff `cps[i]` is inside a preservable tag sequence
 */
function markTagSequences(cps) {
  const keep = new Uint8Array(cps.length);
  for (let i = 0; i < cps.length; i++) {
    if (cps[i] !== TAG_BASE) continue;
    let j = i + 1;
    let payload = "";
    while (j < cps.length && cps[j] >= TAG_SPEC_MIN && cps[j] <= TAG_SPEC_MAX) {
      payload += String.fromCharCode(cps[j] - 0xe0000);
      j++;
    }
    const tagLen = j - (i + 1);
    // Require ≥1 tag char, at most MAX_TAG_SPEC_CHARS, a terminating CANCEL, and
    // a payload naming a registered subdivision — else the run stays stripped.
    if (
      tagLen >= 1 &&
      tagLen <= MAX_TAG_SPEC_CHARS &&
      j < cps.length &&
      cps[j] === TAG_CANCEL &&
      REGISTERED_TAG_PAYLOADS.has(payload)
    ) {
      for (let k = i + 1; k <= j; k++) keep[k] = 1;
      i = j; // resume after the consumed sequence
    }
  }
  return keep;
}

/**
 * True when `cps[i]` is a standardized variation selector (U+FE00–U+FE0D) whose
 * immediately preceding code point forms a REGISTERED standardized variation
 * sequence (per the generated UCD table). Every unregistered FE00–FE0D selector
 * stays payload.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function isStandardizedVariationSelector(cps, i) {
  const cp = cps[i];
  if (cp < 0xfe00 || cp > 0xfe0d) return false;
  return i > 0 ? isStandardizedVariant(cps[i - 1], cp) : false;
}

/**
 * True when `cps[i]` is an ideographic variation selector (VS17–VS256,
 * U+E0100–U+E01EF) immediately after a CJK ideograph — the registry-faithful
 * structural gate for an ideographic variation sequence.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function isIdeographicVariationSelector(cps, i) {
  const cp = cps[i];
  if (cp < IVS_MIN || cp > IVS_MAX) return false;
  return isCjkIdeograph(i > 0 ? cps[i - 1] : -1);
}

/**
 * True when `cps[i]` is a Braille blank (U+2800) or a Hangul filler that sits
 * next to a real, script-appropriate visible neighbour — a genuine empty Braille
 * cell or archaic-Korean filler, not a hidden run. The zero-width Mn marks in
 * BLANK_NON_CF have no such anchored use and are never preserved here.
 * @param {Int32Array} cps @param {number} i
 * @returns {boolean}
 */
function isPreservedBlankFiller(cps, i) {
  const cp = cps[i];
  const prev = i > 0 ? cps[i - 1] : -1;
  const next = i + 1 < cps.length ? cps[i + 1] : -1;
  if (cp === BRAILLE_BLANK) return isBrailleCell(prev) || isBrailleCell(next);
  if (HANGUL_FILLERS.has(cp)) return isHangul(prev) || isHangul(next);
  return false;
}

// The grapheme segmenter: the real UAX #29 implementation shipped with the
// runtime's ICU, not a hand-rolled approximation of cluster boundaries. It
// defines the unit the preserve budget is charged against (see carveStrip).
// Grapheme segmentation is locale-independent, so the locale is pinned to "en"
// only for determinism across hosts.
const GRAPHEME_SEGMENTER = new Intl.Segmenter("en", {
  granularity: "grapheme",
});

/**
 * The UTF-16 index at which each code point of `cps` starts, plus one final
 * entry for the end of the string — the bridge between the code-point space the
 * carve analysis works in and the UTF-16 space `body.slice` and the segmenter
 * speak.
 * @param {Int32Array} cps
 * @returns {Int32Array}
 */
function u16Offsets(cps) {
  const offsets = new Int32Array(cps.length + 1);
  let at = 0;
  for (let i = 0; i < cps.length; i++) {
    offsets[i] = at;
    at += cps[i] > 0xffff ? 2 : 1;
  }
  offsets[cps.length] = at;
  return offsets;
}

/**
 * The code-point index of the UTF-16 index `u16`, by binary search over
 * {@link u16Offsets}. `u16` is always a code-point (indeed a cluster) boundary,
 * so the search always lands exactly.
 * @param {Int32Array} offsets @param {number} u16
 * @returns {number}
 */
function cpIndexOf(offsets, u16) {
  let lo = 0;
  let hi = offsets.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (offsets[mid] < u16) lo = mid + 1;
    else hi = mid;
  }
  return lo;
}

// Above this share of the code points being carve-out CANDIDATES, resolving each
// candidate's cluster with `Segments.containing` costs more than segmenting the
// document once from the start (a `containing` call is a few times dearer than
// one step of the sequential iterator). Both strategies read the SAME segmenter,
// so they return the same boundaries; this only picks the cheaper way to ask.
const CONTAINING_CANDIDATE_SHARE = 4;

/**
 * A source of the grapheme cluster containing a given code-point index, over
 * indices asked for in increasing order.
 *
 * Cluster boundaries matter only where a preservable invisible sits: a cluster
 * with none leaves every counter in {@link carveStrip} untouched, and the emit
 * loop treats each of its code points the same however the boundaries fall. So
 * the clusters are resolved on demand around the candidates rather than by
 * segmenting the whole document — the difference between reading one emoji at
 * the end of an 8 MB log and segmenting the 8 MB.
 * @param {string} body @param {Int32Array} offsets @param {number} candidates
 * @returns {(cp: number) => { start: number, end: number }}
 */
function clusterResolver(body, offsets, candidates) {
  const cpCount = offsets.length - 1;
  if (candidates * CONTAINING_CANDIDATE_SHARE < cpCount) {
    const segments = GRAPHEME_SEGMENTER.segment(body);
    return (cp) => {
      // `offsets[cp]` is inside the string for every code-point index the walk
      // asks about, so the segment always exists.
      const found = /** @type {{ index: number, segment: string }} */ (
        segments.containing(offsets[cp])
      );
      return {
        start: cpIndexOf(offsets, found.index),
        end: cpIndexOf(offsets, found.index + found.segment.length),
      };
    };
  }
  // Dense candidates: walk the segmenter forward instead, keeping a code-point
  // cursor in step with it so no boundary needs searching for. The iterator is
  // abandoned wherever the last candidate leaves it, so a document whose
  // preserve budget is spent in its first line is never segmented past it.
  const iterator = GRAPHEME_SEGMENTER.segment(body)[Symbol.iterator]();
  let start = 0;
  let end = 0;
  return (cp) => {
    while (end <= cp) {
      // ECMA-402 guarantees the segments partition the input, so every code
      // point inside it has a cluster and the iterator cannot run out first; if
      // it ever did, reading `.segment` off `undefined` throws here rather than
      // silently answering with a boundary nobody computed.
      const step = /** @type {{ value: { segment: string } }} */ (
        iterator.next()
      );
      start = end;
      end = cpIndexOf(offsets, offsets[start] + step.value.segment.length);
    }
    return { start, end };
  };
}

/**
 * Carve-out strip (an invisible the carve-out might preserve is present): walk
 * GRAPHEME CLUSTERS, preserving a cluster's joiners/selectors/tags only where
 * each has its `kind` set AND the text stays under the scatter floor AND the
 * whole cluster fits inside the remaining per-run (CONSECUTIVE_JOINER_CAP /
 * CONSECUTIVE_SELECTOR_CAP) and document-wide (TOTAL_PRESERVED_JOINER_BUDGET)
 * preserve allowance — otherwise every preservable char in that cluster is
 * stripped like any other payload byte. Blank fillers are the exception: their
 * allowance is anchor-proportional and already spent document-wide in
 * analyzeCarve (see PRESERVED_BLANK_PER_ANCHOR), so here they answer only to
 * the scatter floor and do not draw on the joiner/selector budget.
 *
 * The budget is charged against the CLUSTER, not the code point, because the
 * cluster is the indivisible unit: charging per code point let a limit fall due
 * mid-cluster and carve one grapheme in half (👨‍👩‍👧‍👦 with the budget exhausted
 * after its first ZWJ came out as 👨‍👩👧👦 — three glyphs where the author wrote
 * one). All-or-nothing per cluster makes that impossible by construction rather
 * than merely unlikely, and it subsumes the tag (subregional-flag) sequence's
 * hand-rolled atomicity: a flag's tag chars are Grapheme_Cluster_Break=Extend,
 * so they are already inside their base pictograph's cluster.
 *
 * `found` reports only categories actually removed, so a preserved char never
 * makes the caller claim a strip that did not happen, and a stuffed channel
 * surfaces as its category once it overruns the budget.
 * @param {string} body
 * @param {Int32Array} [cps]  `body`'s code points, when the caller already has them
 * @param {ReturnType<typeof analyzeCarve>} [analysis]  likewise the analysis
 * @returns {{ cleaned: string, found: string[] }}
 */
function carveStrip(
  body,
  cps = codePointArray(body),
  analysis = analyzeCarve(cps),
) {
  // Only PAYLOAD invisibles count toward the scatter floor, so a
  // meaningful-joiner-dense text (formal Persian, a long Devanagari conjunct
  // run) stays under it.
  const { codes, kind, payloadInvis, visibleLen } = analysis;
  // SCATTERED_THRESHOLD is the floor on payload invisibles: past it the document
  // is drowning in hidden bytes, so the carve-out is off and even a meaningful
  // joiner is stripped (threshold-evasion catch — over-strip beats under).
  const allowCarveOut = payloadInvis < SCATTERED_THRESHOLD;
  // Document-wide preserve allowance, proportional to visible text but never
  // below the floor (see TOTAL_PRESERVED_JOINER_BUDGET / PRESERVED_JOINER_PER_VISIBLE)
  // and never above PRESERVE_HARD_CAP — the absolute ceiling stops the channel
  // scaling with attacker-supplied cover text.
  const maxPreserved = Math.min(
    PRESERVE_HARD_CAP,
    Math.max(
      TOTAL_PRESERVED_JOINER_BUDGET,
      Math.ceil(visibleLen / PRESERVED_JOINER_PER_VISIBLE),
    ),
  );

  const n = cps.length;
  // Every code point that draws on the joiner/selector budget, in order. Blank
  // fillers are exempt (their allowance is already spent in analyzeCarve), so a
  // cluster holding only those needs no boundary of its own.
  /** @type {number[]} */
  const candidates = [];
  if (allowCarveOut)
    for (let k = 0; k < n; k++)
      if (kind[k] !== KIND_NONE && kind[k] !== KIND_BLANK) candidates.push(k);

  const foundCodes = new Set();
  /** @type {string[]} */
  const kept = [];
  const offsets = u16Offsets(cps);
  // Start of the kept run currently being accumulated, in UTF-16 units. Output
  // is assembled from slices of `body` — one per uninterrupted kept run — rather
  // than a character at a time, so a document with nothing to strip costs one
  // slice however long it is.
  let runStart = 0;
  // Preserved JOINERS in the current uninterrupted cluster (tags/blank fillers
  // and presentation selectors don't chain, so they are exempt). A genuine gap
  // (two visible chars in a row — see prevVisible) resets it; past the cap the
  // surplus is stripped.
  let joinerRun = 0;
  // Preserved IVS/standardized variation selectors in the current uninterrupted
  // run (an `ideograph selector ideograph selector …` chain never breaks the
  // prevVisible gap, so joinerRun's reset does not bound it — this counter does).
  // Same genuine-gap reset as joinerRun; past CONSECUTIVE_SELECTOR_CAP the
  // surplus is stripped, closing the high-bit-rate variation-selector channel.
  let selectorRun = 0;
  // Preserved chars across the WHOLE string — never reset at a gap, so it bounds
  // the document-wide channel joinerRun cannot. Past maxPreserved a preserved
  // char is stripped and its category reported.
  let preservedTotal = 0;
  let prevVisible = false;

  /** Emit `[from, to)` under a settled `fits`, updating every counter.
   * @param {number} from @param {number} to @param {boolean} fits */
  const emit = (from, to, fits) => {
    for (let k = from; k < to; k++) {
      const code = codes[k];
      if (code === CODE_VISIBLE) {
        // A visible char following another visible char is a real word/segment
        // boundary, not a join — the joined cluster (if any) ended here.
        if (prevVisible) {
          joinerRun = 0;
          selectorRun = 0;
        }
        prevVisible = true;
        continue; // ordinary visible character: stays inside the kept run
      }
      // A blank filler rides on allowCarveOut alone (its own allowance is
      // already spent in analyzeCarve); everything else rides on `fits`.
      if (
        kind[k] === KIND_BLANK ? allowCarveOut : fits && kind[k] !== KIND_NONE
      ) {
        if (kind[k] === KIND_JOINER) joinerRun++;
        if (kind[k] === KIND_IVS || kind[k] === KIND_STDVS) selectorRun++;
        if (kind[k] !== KIND_BLANK) preservedTotal++;
        prevVisible = false; // a joiner/selector/tag/blank keeps the cluster open
        continue;
      }
      foundCodes.add(CODE_CATEGORY[code]);
      prevVisible = false; // a stripped invisible neither opens nor closes a gap
      if (offsets[k] > runStart) kept.push(body.slice(runStart, offsets[k]));
      runStart = offsets[k + 1];
    }
  };

  const clusterOf =
    candidates.length > 0
      ? clusterResolver(body, offsets, candidates.length)
      : null;
  // The last index at which the emit loop resets the run counters — a visible
  // code point directly after another visible one. The condition reads only
  // `codes`, never a preserve decision, so the whole set of reset points is
  // known before the walk starts. Past this index the run counters can only
  // ever be incremented, which is what makes the exhaustion test below final.
  let lastGap = -1;
  // Remaining candidates by the limit each one draws on, decremented as the
  // walk passes them.
  let leftJoiner = 0;
  let leftSelector = 0;
  let leftOther = 0;
  if (clusterOf !== null) {
    for (let i = n - 1; i > 0; i--)
      if (codes[i] === CODE_VISIBLE && codes[i - 1] === CODE_VISIBLE) {
        lastGap = i;
        break;
      }
    for (const c of candidates) {
      if (kind[c] === KIND_JOINER) leftJoiner++;
      else if (kind[c] === KIND_IVS || kind[c] === KIND_STDVS) leftSelector++;
      else leftOther++;
    }
  }

  /** True when no cluster from here on can be preserved, so the rest of the
   * document is settled and needs no boundaries. Every term is monotone:
   * `preservedTotal` only grows, and past `lastGap` the run counters only grow
   * too, so a limit that is spent here is spent for good.
   * @param {number} at */
  const nothingLeftFits = (at) => {
    if (preservedTotal >= maxPreserved) return true;
    if (at <= lastGap) return false; // a reset ahead can reopen a spent run
    if (leftOther > 0) return false; // a tag/presentation selector draws on neither run
    if (leftJoiner > 0 && joinerRun < CONSECUTIVE_JOINER_CAP) return false;
    if (leftSelector > 0 && selectorRun < CONSECUTIVE_SELECTOR_CAP)
      return false;
    return true;
  };

  let k = 0;
  let next = 0;
  while (k < n) {
    while (next < candidates.length && candidates[next] < k) next++;
    if (
      clusterOf === null ||
      next === candidates.length ||
      nothingLeftFits(k)
    ) {
      emit(k, n, false);
      break;
    }
    const { start, end } = clusterOf(candidates[next]);
    if (start > k) emit(k, start, false);
    // Charge the WHOLE cluster's preservables against every limit at once: if
    // any one of them would fall due part-way through, none of the cluster is
    // preserved.
    let need = 0;
    let joiners = 0;
    let selectors = 0;
    for (let j = start; j < end; j++) {
      if (kind[j] === KIND_NONE || kind[j] === KIND_BLANK) continue;
      need++;
      if (kind[j] === KIND_JOINER) joiners++;
      if (kind[j] === KIND_IVS || kind[j] === KIND_STDVS) selectors++;
    }
    // The run counters as they stand at the cluster's FIRST preservable char.
    // A cluster can OPEN with a genuine gap — two visible code points in a row,
    // e.g. the second of two adjacent emoji ZWJ sequences, or a letter and its
    // harakat — which the emit loop resets on. Judging the caps on the stale
    // pre-reset count would strip joiners the cap never meant to catch: a false
    // positive on legitimate joined text. This mirrors the emit loop's gap rule
    // exactly (only a visible char after another visible char closes a run; any
    // invisible, payload included, does not) and stops at the first preservable,
    // since resets past it are the emit loop's business.
    let runJoiner = joinerRun;
    let runSelector = selectorRun;
    let seenVisible = prevVisible;
    for (let j = start; j < end && kind[j] === KIND_NONE; j++) {
      if (codes[j] === CODE_VISIBLE && seenVisible) {
        runJoiner = 0;
        runSelector = 0;
      }
      seenVisible = codes[j] === CODE_VISIBLE;
    }
    for (let j = next; j < candidates.length && candidates[j] < end; j++) {
      if (kind[candidates[j]] === KIND_JOINER) leftJoiner--;
      else if (
        kind[candidates[j]] === KIND_IVS ||
        kind[candidates[j]] === KIND_STDVS
      )
        leftSelector--;
      else leftOther--;
    }
    emit(
      start,
      end,
      preservedTotal + need <= maxPreserved &&
        runJoiner + joiners <= CONSECUTIVE_JOINER_CAP &&
        runSelector + selectors <= CONSECUTIVE_SELECTOR_CAP,
    );
    k = end;
  }
  kept.push(body.slice(runStart));
  const found = CHECKS.filter(([code]) => foundCodes.has(code)).map(
    ([code]) => code,
  );
  return { cleaned: kept.join(""), found };
}

// Any tag char (the whole U+E0000–U+E007F block is category Cf).
const TAG_CHAR_RE = /[\u{E0000}-\u{E007F}]/u;

/**
 * True when `body` holds anything the carve-out in {@link carveStrip} might
 * preserve: a ZWNJ/ZWJ, ANY variation selector (a registered standardized or
 * ideographic sequence, or an emoji presentation selector — VARIATION_SELECTOR
 * covers FE00–FE0F and E0100–E01EF), a tag char (a subregional flag), or a
 * gated blank filler (Braille/archaic-Hangul). Each needs the per-neighbor
 * analysis, or bulkStrip would strip it unconditionally and corrupt a
 * legitimate glyph.
 * @param {string} body
 * @returns {boolean}
 */
function needsCarveOut(body) {
  return (
    body.includes(String.fromCodePoint(ZWNJ)) ||
    body.includes(String.fromCodePoint(ZWJ)) ||
    VARIATION_SELECTOR.test(body) ||
    TAG_CHAR_RE.test(body) ||
    GATED_BLANK_RE.test(body)
  );
}

/**
 * The `text` with every carve-out-PRESERVABLE invisible (joiners/selectors/tags/
 * blank fillers doing real rendering work) replaced by a space, leaving only the
 * PAYLOAD invisibles in place. The LONG_RUN injection probe runs over this so a
 * legitimate emoji/flag/variation sequence never trips the "possible injection
 * payload" marker (alert fatigue), while a genuine hidden run still surfaces.
 * @param {string} text
 * @returns {string}
 */
export function payloadInvisibleView(text) {
  const cps = codePointArray(text);
  const { codes, kind } = analyzeCarve(cps);
  const offsets = u16Offsets(cps);
  /** @param {number} i */
  const isPayload = (i) => codes[i] !== CODE_VISIBLE && kind[i] === KIND_NONE;
  // Written a RUN at a time — one `" ".repeat(n)` per masked stretch, one slice
  // of `text` per payload stretch — because the two stretches alternate a
  // handful of times in a real document and once per character in none of them.
  /** @type {string[]} */
  const parts = [];
  let i = 0;
  while (i < cps.length) {
    const maskFrom = i;
    while (i < cps.length && !isPayload(i)) i++;
    // One space per masked CODE POINT, so the view stays code-point-aligned with
    // `text` even where an astral character is two UTF-16 units wide.
    if (i > maskFrom) parts.push(" ".repeat(i - maskFrom));
    const keepFrom = i;
    while (i < cps.length && isPayload(i)) i++;
    if (i > keepFrom) parts.push(text.slice(offsets[keepFrom], offsets[i]));
  }
  return parts.join("");
}

/**
 * The first payload-invisible LONG RUN in `text`, or null when there is none.
 *
 * THE definition of "this text carries a hidden run", shared by every consumer
 * that has an opinion about one: the strip's `[LONG RUN — possible injection
 * payload]` marker, the prompt gate's block decision, and the tool-output
 * severity tier. They used to spell it twice, and differently — the marker
 * probed the PAYLOAD view while the prompt gate probed the raw text, so a
 * legitimate ten-emoji flag sequence (carve-out-preserved, never stripped) was
 * quietly enough to BLOCK a prompt while the strip that saw the same text
 * declined to even flag it. Masking the preserved invisibles is the right half
 * of that disagreement: a run the carve-out keeps is rendering work, not a
 * channel, and the joiners it does NOT keep are counted as payload anyway (see
 * {@link countEffectiveInvisible}).
 *
 * Because the view replaces only PRESERVED invisibles (and visible characters)
 * with spaces, a match consists solely of payload code points and is therefore
 * byte-identical to the corresponding span of `text` — so a caller may report
 * the sample verbatim.
 * @param {string} text
 * @returns {string | null}
 */
export function payloadLongRunSample(text) {
  // The view is code-point-for-code-point with `text` and only ever REPLACES an
  // invisible with a space, so a run in the view is a run in `text`: no long run
  // in the raw text means none in the view. This hides no payload — the bulk
  // scan reads the whole text, and a run it finds still goes through the full
  // carve analysis below to decide what of it is really payload.
  if (!hasLongRun(text)) return null;
  return findLongRuns(payloadInvisibleView(text)).next().value?.text ?? null;
}

/**
 * How many invisible code points in `text` the strip layer treats as PAYLOAD:
 * the ones {@link countPayloadInvisible} counts, plus the joiners that sit in a
 * genuine linguistic context but exceed the carve-out's preservation budget.
 *
 * The surplus term closes the preserved-joiner covert channel (O3):
 * `countPayloadInvisible` excludes every ZWNJ/ZWJ doing real rendering work, so
 * an attacker who alternates `letter joiner letter joiner …` — every joiner
 * legitimately between two cursive letters — counts as ZERO there. The strip
 * layer already refuses that (it preserves joiners only up to
 * TOTAL_PRESERVED_JOINER_BUDGET / CONSECUTIVE_JOINER_CAP and strips the rest),
 * so the surplus is read back OFF the strip — the SSOT — rather than by
 * re-deriving the budget here, which is what would drift.
 *
 * A leading BOM is preserved by the strip but counted by
 * {@link countPayloadInvisible}, so the difference can go slightly negative;
 * hence the clamp.
 * @param {string} text  ANSI-stripped text (an escape sequence can hide invisibles)
 * @returns {number}
 */
export function countEffectiveInvisible(text) {
  // A text with no invisible code point has no payload and nothing to strip, so
  // it needs neither the code-point array nor the carve analysis. This reads
  // every code point — a necessary condition checked in full, not a scan bound
  // an attacker could paste past.
  if (!hasInvisibleCodePoint(text)) return 0;
  // A leading BOM is sliced off before the strip but counted by the analysis, so
  // the two would read different strings; that case pays for both separately.
  if (text.charCodeAt(0) === 0xfeff)
    return surplusOver(countPayloadInvisible(text), text, stripInvisible(text));
  // Otherwise both terms are readings of ONE carve analysis of ONE string, so
  // the analysis is done once and handed to the strip.
  const cps = codePointArray(text);
  const analysis = analyzeCarve(cps);
  const { cleaned } = stripBody(text, cps, analysis);
  return surplusOver(analysis.payloadInvis, text, cleaned, cps.length);
}

/**
 * The payload count plus the code points the strip removed BEYOND it — the
 * carve-out's over-budget surplus (see {@link countEffectiveInvisible}). A
 * leading BOM is preserved by the strip but counted as payload, so the
 * difference can go slightly negative; hence the clamp.
 * @param {number} payload @param {string} text @param {string} stripped
 * @param {number} [cpLen]  `text`'s code-point length, when already known
 * @returns {number}
 */
function surplusOver(payload, text, stripped, cpLen) {
  // Two identical strings differ by zero code points, so the common clean paste
  // skips both counting passes; codePointLength is the String iterator's count,
  // the same unit `[...text].length` measures, without the array.
  const removed =
    stripped === text
      ? 0
      : (cpLen ?? codePointLength(text)) - codePointLength(stripped);
  return payload + Math.max(0, removed - payload);
}

/**
 * True when the invisible characters in `text` are INCIDENTAL: no hidden run,
 * and too few of them in total to carry an instruction.
 *
 * This is a severity line, not a strip line — the bytes are removed either way
 * (see ../src/severity.mjs). It exists because a single soft hyphen in a
 * pasted paragraph, or one variation selector a font demanded, raised the exact
 * `WARNING: Tool output sanitized` an encoded payload does, and a warning that
 * fires on a stray character in ordinary prose is one operators learn to skip.
 *
 * The bar is {@link LONG_RUN_THRESHOLD} — the count this module already calls
 * "payload length" — applied to the WHOLE text rather than to one run, so it is
 * strictly stronger than the run probe: fewer than ten payload-invisible code
 * points, however they are distributed, cannot spell a smuggled instruction (ten
 * tag characters are ten ASCII letters). Deliberately NOT the far looser
 * {@link SCATTERED_THRESHOLD} of 30, which is the prompt gate's BLOCK bar: 29
 * tag characters is a short sentence, and staying quiet about a short sentence
 * hidden in a tool result is not a trade worth making.
 * @param {string} text  ANSI-stripped text, invisible runs intact
 * @returns {boolean}
 */
export function isIncidentalInvisible(text) {
  return (
    payloadLongRunSample(text) === null &&
    countEffectiveInvisible(text) < LONG_RUN_THRESHOLD
  );
}

/**
 * Strip payload-capable invisible chars and report which categories were
 * removed. A single leading U+FEFF (BOM) is preserved as a legitimate marker;
 * interior BOMs and all soft hyphens (U+00AD) are stripped, since either can
 * encode hidden instructions. ZWNJ/ZWJ survive only in a linguistic context
 * (see the carve-out above). `found` names exactly the categories stripped, so
 * a caller never warns about a strip the carve-out skipped.
 *
 * `originalText` is the pre-processing text (before any ANSI strip) used ONLY to
 * decide whether a leading BOM is genuinely leading: an interior BOM that an
 * ANSI-strip left at index 0 of `text` (e.g. `ESC[m + interior U+FEFF`) must NOT be treated as a
 * legitimate leading marker. Defaults to `text` for the common single-arg call.
 * @param {string} text
 * @param {string} [originalText]
 * @returns {{ cleaned: string, found: string[] }}
 */
export function stripInvisibleWithReport(text, originalText = text) {
  // Leading only when the BOM leads the ORIGINAL text (not merely `text` after an
  // ANSI strip shifted an interior BOM to index 0). The `text` guard keeps the
  // slice sound when the two disagree.
  const hasLeadingBom =
    originalText.charCodeAt(0) === 0xfeff && text.charCodeAt(0) === 0xfeff;
  const body = hasLeadingBom ? text.slice(1) : text;
  const { cleaned, found } = stripBody(body);
  return { cleaned: hasLeadingBom ? BOM + cleaned : cleaned, found };
}

/**
 * The strip of a BOM-resolved body: the carve-out walk when anything in it could
 * be preserved, the single bulk regex pass otherwise. `cps` and `analysis` let a
 * caller that has already analyzed `body` hand the work over instead of paying
 * for it twice.
 * @param {string} body
 * @param {Int32Array} [cps]
 * @param {ReturnType<typeof analyzeCarve>} [analysis]
 * @returns {{ cleaned: string, found: string[] }}
 */
function stripBody(body, cps, analysis) {
  if (!needsCarveOut(body)) return bulkStrip(body);
  return carveStrip(body, cps, analysis);
}

/**
 * Strip payload-capable invisible chars (cleaned text only). See
 * stripInvisibleWithReport for the BOM and ZWNJ/ZWJ carve-out semantics.
 * @param {string} text
 * @returns {string}
 */
export function stripInvisible(text) {
  return stripInvisibleWithReport(text).cleaned;
}
