/**
 * Invisible-character + ANSI/SGR primitives with no external runtime deps.
 *
 * Removes payload-capable Unicode (general-category Cf format chars, variation
 * selectors, blank-rendering fillers, soft hyphens, interior BOMs) while
 * preserving ZWNJ/ZWJ in genuine linguistic and emoji contexts, and reports
 * which categories were removed. The linguistic carve-out is driven by the
 * generated Unicode Joining_Type / virama tables in ./joining-type.mjs (a
 * sibling data module, not a package), so it decides preservation from the
 * actual cursive-join semantics rather than a hand-rolled script guess.
 */
import { joiningType, isVirama, isBrahmicConsonant } from "./joining-type.mjs";
import { isStandardizedVariant } from "./standardized-variants.mjs";
import { CF_CODEPOINTS } from "./cf-charset.mjs";
import { scanAnsi, TOKEN_KIND } from "./ansi.mjs";

// Unicode's Variation_Selector property, whole: the FE00 run, the Mongolian
// free variation selectors, and the astral E0100 supplement. The Mongolian four
// are general category Mn, so \p{Cf} does not reach them and CF_CODEPOINTS
// carries only U+180E (the vowel SEPARATOR) — without them a run of U+180B..D
// renders as nothing, survives untouched, and counts as VISIBLE length, which
// also widens the preserved-joiner budget.
export const VS = [
  ...Array.from({ length: 16 }, (_, i) => 0xfe00 + i),
  0x180b,
  0x180c,
  0x180d,
  0x180f,
  ...Array.from({ length: 240 }, (_, i) => 0xe0100 + i),
]
  .map((codePoint) => String.fromCodePoint(codePoint))
  .join("");

// Combining marks (general category Mn) that carry NO advance width \u2014 they
// render as nothing on their own, so a run of them is a hidden channel exactly
// like a zero-width Cf char, yet \p{Cf} misses them (they are Mn). Strictly
// enumerated, one reason per entry, because MOST Mn marks DO have visible width
// (accents, vowel signs) and must never be stripped \u2014 only these zero-advance
// ones qualify. Driven as an SSOT so the test iterates one case per member.
//   U+034F COMBINING GRAPHEME JOINER \u2014 invisible; affects only collation/shaping
//   U+17B4 KHMER VOWEL INHERENT AQ   \u2014 zero-width inherent vowel, renders blank
//   U+17B5 KHMER VOWEL INHERENT AA   \u2014 zero-width inherent vowel, renders blank
export const ZERO_WIDTH_MN = "\u034F\u17B4\u17B5";

// Code points that render blank / zero-width but are NOT general category Cf,
// so the \p{Cf} check below misses them: the Hangul fillers (category Lo,
// U+115F/U+1160/U+3164/U+FFA0), the Braille blank pattern (category So,
// U+2800), and the zero-width combining marks above (category Mn). A run of any
// of these carries a hidden payload exactly as zero-widths do.
export const BLANK_NON_CF = "\u115F\u1160\u3164\uFFA0\u2800" + ZERO_WIDTH_MN;

const REGEX_FLAGS = "gu";

// A regex character-class source (`[…]`, `u`-flag) matching EXACTLY the pinned
// Cf code points in CF_CODEPOINTS — the version-locked stand-in for a live
// `\p{Cf}` test. Node (U17) and the CPython interpreter the Python port runs on
// (often U14/U15) disagree on `\p{Cf}`, so testing `\p{Cf}` live here would strip
// a DIFFERENT set than the port and let a key spliced with a code point in the
// version delta (e.g. U+13439) escape the older-Unicode layer. Reading the pinned
// set (generated by scripts/gen-invisible-charset.mjs, the same list the port
// reads from data/invisible-charset.json) closes that cross-layer gap. Consecutive
// code points collapse to `\u{a}-\u{b}` ranges so the class stays compact.
/** @param {readonly number[]} codepoints @returns {string} */
function cfClassSource(codepoints) {
  const sorted = [...codepoints].sort((a, b) => a - b);
  let src = "[";
  for (let i = 0; i < sorted.length;) {
    let j = i;
    while (j + 1 < sorted.length && sorted[j + 1] === sorted[j] + 1) j++;
    src += `\\u{${sorted[i].toString(16)}}`;
    if (j > i) src += `-\\u{${sorted[j].toString(16)}}`;
    i = j + 1;
  }
  return src + "]";
}

const CF_CLASS_SOURCE = cfClassSource(CF_CODEPOINTS);

// Stable, machine-readable category codes for the `found` array returned by
// stripInvisibleWithReport and sanitize. These are API: branch on them. They
// are deliberately NOT the human-facing prose (that lives in `warnings` and in
// CATEGORY_LABELS), so the display wording can be reworded without a breaking
// change to anyone matching on `found`.
export const CATEGORY = Object.freeze({
  CF: "cf-format",
  VARIATION_SELECTORS: "variation-selectors",
  BLANK_FILLERS: "blank-fillers",
  ANSI: "ansi",
  LONE_SURROGATES: "lone-surrogates",
  HTML_COMMENTS: "html-comments",
  HIDDEN_HTML: "hidden-html",
  EXFIL_URLS: "exfil-urls",
});

// code -> human label, used only to build `warnings` text. Decoupled from
// CATEGORY so prose changes never alter the machine-readable `found` contract.
/** @type {Readonly<Record<string, string>>} */
export const CATEGORY_LABELS = Object.freeze({
  [CATEGORY.CF]: "Format chars (Cf)",
  [CATEGORY.VARIATION_SELECTORS]: "Variation selectors",
  [CATEGORY.BLANK_FILLERS]: "Blank-rendering fillers",
  [CATEGORY.ANSI]: "ANSI escapes",
  [CATEGORY.LONE_SURROGATES]: "Lone UTF-16 surrogates",
  [CATEGORY.HTML_COMMENTS]: "HTML comments",
  [CATEGORY.HIDDEN_HTML]: "hidden HTML",
  [CATEGORY.EXFIL_URLS]: "exfil URLs",
});

/** @type {Array<[string, RegExp]>} Each entry pairs a CATEGORY code with its detector. */
export const CHECKS = [
  [CATEGORY.CF, new RegExp(CF_CLASS_SOURCE, REGEX_FLAGS)],
  [CATEGORY.VARIATION_SELECTORS, new RegExp(`[${VS}]`, REGEX_FLAGS)],
  // BLANK_NON_CF includes zero-width COMBINING marks (Mn: U+034F/17B4/17B5). In
  // a `u`-flag class each matches its own single code point — exactly the intent
  // (we strip the lone mark, never a base+mark grapheme), so the
  // misleading-character-class heuristic is a false positive here.
  // eslint-disable-next-line no-misleading-character-class -- single-code-point matches under the u flag are intentional
  [CATEGORY.BLANK_FILLERS, new RegExp(`[${BLANK_NON_CF}]`, REGEX_FLAGS)],
];

export const STRIP = new RegExp(
  CHECKS.map(([, regex]) => regex.source).join("|"),
  REGEX_FLAGS,
);

// SGR (Select Graphic Rendition) colour matching. Re-exported from ./ansi.mjs —
// the ONE ANSI grammar, shared with the Layer-1 stripper, which cannot import
// this module (layer1.mjs imports invisible.mjs, not the other way round). The
// two used to be separate regexes with DIFFERENT parameter rules, and the looser
// copy lived here: `ESC[12345m` read as SGR-only (so the operator got a
// "display-only colour" note) while the stripper could not match it and spliced
// a visible `[12345m` into the model's view.
export { SGR_RE } from "./ansi.mjs";

/**
 * True when every ANSI control introducer in `text` belongs to a display-only
 * SGR color sequence (so stripping the ANSI removes only cosmetic styling,
 * nothing that could move the cursor, erase, or carry a payload). Recognizes
 * both the 7-bit `ESC[…m` and 8-bit C1 (`U+009B…m`) SGR encodings.
 *
 * Answered by the STRIPPER'S OWN tokenizer: scanAnsi emits one token per raw
 * introducer — 7-bit ESC and the whole C1 block, so a C1 cursor-move
 * (`U+009B 2J`), a C1-OSC string (`U+009D … BEL`), a C1-DCS/APC payload and a
 * lone or partial escape each yield a non-SGR token — and the predicate is
 * "every token is SGR". Because the same scan decides what Layer 1 splices,
 * this can no longer report "colour only" for bytes the stripper leaves behind.
 * @param {string} text
 * @returns {boolean}
 */
export function isSgrOnly(text) {
  return scanAnsi(text).every((token) => token.kind === TOKEN_KIND.SGR);
}

export const LONG_RUN_THRESHOLD = 10;

/** Total invisible-char count above which a file/prompt is treated as
 * payload-capable even without a long run (threshold-evasion catch). */
export const SCATTERED_THRESHOLD = 30;

export const LONG_RUN_RE = new RegExp(
  `(?:${STRIP.source}){${LONG_RUN_THRESHOLD},}`,
  REGEX_FLAGS,
);

/**
 * The agent-facing "Stripped: …" note for a Layer-1 strip: the removed category
 * labels, the LONG RUN marker when the de-ANSI'd text still holds a
 * payload-length invisible run, and a pointer to recover the bytes — a hex dump
 * is ASCII, so it passes through sanitization untouched. The single source of
 * this note, shared by the `sanitize` convenience entry and the tool-output
 * pipeline so the two can't drift.
 * @param {string[]} invisFound CATEGORY codes applyLayer1 reported removing
 * @param {string} deAnsi ANSI-stripped text (invisible runs intact), for the LONG_RUN probe
 * @returns {string}
 */
export function describeStripped(invisFound, deAnsi) {
  let msg = `Stripped: ${invisFound.map((code) => CATEGORY_LABELS[code]).join(", ")}`;
  LONG_RUN_RE.lastIndex = 0;
  // Probe only the PAYLOAD invisibles: a legitimate emoji/flag/variation
  // sequence is carve-out-preserved and masked out here, so it never trips the
  // injection marker (alert fatigue) while a genuine hidden run still surfaces.
  if (LONG_RUN_RE.test(payloadInvisibleView(deAnsi)))
    msg += " [LONG RUN — possible injection payload]";
  return (
    msg +
    " — inspect the removed bytes with a hex dump (xxd / od -c), which survives sanitization"
  );
}

// Leading-BOM marker, preserved by stripInvisibleWithReport (see its doc).
const BOM = "\uFEFF";
// ─── ZWNJ/ZWJ linguistic carve-out ───────────────────────────────────────────
// ZWNJ (U+200C) and ZWJ (U+200D) are general category Cf, so the STRIP pass
// would treat them as hidden-payload bytes. But they are MANDATORY for correct
// rendering between letters of several scripts (Arabic/Persian and many Indic
// scripts) and inside emoji ZWJ sequences — blanket stripping corrupts
// legitimate non-English output. Preserve them only where they do real
// rendering work, decided SYNTACTICALLY from the neighbours' Unicode
// Joining_Type (see isPreservedJoiner): a joiner between two cursive letters, an
// Indic joiner after a virama, an emoji joiner between emoji components. Strip
// them as payload everywhere else — leading/trailing, next to a non-joining
// character (ASCII, punctuation, a non-connecting letter), or inside a joiner
// run. Over-strip beats under-strip only on genuine ambiguity; a joiner sitting
// between two real cursive letters is treated as content and kept.
const ZWNJ = 0x200c;
const ZWJ = 0x200d;

// Max joiners the carve-out will PRESERVE within one uninterrupted joined
// cluster (a `letter (joiner letter)*` chain, or an emoji ZWJ sequence). A real
// word or emoji glyph needs only a handful in a row — the longest standard emoji
// ZWJ sequences (family-of-four, profession+ZWJ) carry three; a Persian
// compound a couple. Past this many consecutive PRESERVED joiners with no real
// gap between them, the chain is treated as a zero-width payload channel (an
// attacker alternates `letter joiner letter joiner …` so every joiner still sits
// between two cursive letters) and the surplus joiners are stripped. The counter
// resets at any genuine gap — two visible characters in a row, i.e. text that is
// NOT part of a joined cluster — so an ordinary single joiner per word is kept.
export const CONSECUTIVE_JOINER_CAP = 8;

// Max variation selectors the carve-out preserves in one uninterrupted run of
// selected glyphs (an `ideograph selector ideograph selector …` chain, or the
// standardized-variation equivalent). Each selector encodes up to a byte, so an
// attacker who variant-selects every character of a CJK/base run opens a
// high-bit-rate channel that the joiner cap does not touch (these are not
// joiners). A genuine document variant-selects only the odd rare glyph, never a
// long unbroken run, so past this many consecutive PRESERVED IVS/stdvs with no
// real gap the surplus is stripped. The counter resets at a genuine gap (two
// visible characters in a row), exactly like CONSECUTIVE_JOINER_CAP.
export const CONSECUTIVE_SELECTOR_CAP = 8;

// Floor on the document-wide preserve budget, shared by both preserve kinds
// (see `kind` in analyzeCarve: joiners AND presentation selectors draw from
// the same counter). The Joining_Type gate strips joiners that do no
// rendering work regardless of count, so the bulk covert channel (ZWNJ
// scattered through Latin/ASCII/mixed text) is closed by shape, not by
// counting. What remains is the residual channel of MEANINGFUL joiners/
// selectors stuffed into genuine cover text — each individually legitimate,
// so indistinguishable one at a time. THIS budget (with CONSECUTIVE_JOINER_CAP
// and SCATTERED_THRESHOLD) is the explicit, tunable bound on that residual
// channel; it is not derived, and tightening it trades covert-channel width for
// clipping genuinely dense prose or emoji-dense text. The allowance is
// proportional to visible length (PRESERVED_JOINER_PER_VISIBLE), never below
// this floor; the floor keeps short but joiner/selector-dense strings (a lone
// emoji ZWJ sequence, a two-word Persian phrase) un-flagged. Past the
// allowance the surplus is stripped AND reported.
export const TOTAL_PRESERVED_JOINER_BUDGET = 16;

// Visible code points required per additional preserved joiner above the floor.
// Measured formal/literary Persian runs ~1 ZWNJ per 5 words (~25 visible chars);
// 1-per-8 sits comfortably above real prose density while still bounding the
// residual channel to a fixed fraction of the cover text.
export const PRESERVED_JOINER_PER_VISIBLE = 8;

// Absolute ceiling on the document-wide preserve allowance, regardless of how
// much visible cover text an attacker supplies. Without it, maxPreserved grows
// linearly with visible length (visibleLen / PRESERVED_JOINER_PER_VISIBLE), so a
// large benign-looking body lets the residual joiner/selector channel scale with
// attacker input — preserved chars do not count toward the scatter floor, so
// nothing else bounds it. This caps the whole channel at a fixed width no cover
// text can widen.
export const PRESERVE_HARD_CAP = 64;

// Scripts whose orthography uses ZWNJ/ZWJ between letters as a rendering
// control. The runtime gate is now script-agnostic (it reads Joining_Type, so it
// covers every cursive/Brahmic script, not just these), but this list remains
// the public, TESTED SSOT of the scripts the carve-out is designed for: the
// suite drives one preserve-case per entry, so a regression in any of them
// fails.
export const LINGUISTIC_SCRIPTS = [
  "Arabic",
  "Devanagari",
  "Bengali",
  "Gurmukhi",
  "Gujarati",
  "Oriya",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Sinhala",
];
// Left side of an emoji joiner: a pictograph or a skin-tone modifier (a base
// emoji may carry a modifier before the joiner, e.g. a health-worker sequence).
const EMOJI_LEFT = /[\p{Extended_Pictographic}\p{Emoji_Modifier}]/u;
// The three keycap bases (digit, `#`, `*`) Unicode's keycap grammar allows
// before VS16 + U+20E3 COMBINING ENCLOSING KEYCAP (1️⃣ #️⃣ *️⃣ … 9️⃣). None is
// Extended_Pictographic or Emoji_Modifier, so EMOJI_LEFT misses them; the
// presentation-selector check accepts one ONLY when the required U+20E3 keycap
// actually follows the selector (see isEmojiPresentationSelector). A bare
// digit/`#`/`*` + VS with no keycap is NOT a glyph — it is a hidden presentation
// selector spliced after ordinary text, the top low-effort VS-smuggling shape —
// so it fails closed and is stripped. The base set is confined to the keycap
// check (never folded into EMOJI_LEFT) so it cannot loosen the ZWJ carve-out.
const KEYCAP_BASE = /[0-9#*]/u;
// U+20E3 COMBINING ENCLOSING KEYCAP — the mandatory terminator of a keycap
// sequence, the one signal that a digit/`#`/`*` + VS16 is a real glyph.
const COMBINING_KEYCAP = 0x20e3;
// Right side of an emoji joiner is always the next component's base pictograph.
const EMOJI_BASE = /\p{Extended_Pictographic}/u;
// A variation selector legitimately sits between a base pictograph and a
// following ZWJ (🏳️‍🌈 = flag base, VS16, ZWJ, rainbow; 👁️‍🗨️), so the joiner's real
// left neighbor for the emoji test is the pictograph, not the selector.
const VARIATION_SELECTOR = new RegExp(`[${VS}]`, "u");
// U+FE0F (VS16) forces emoji presentation, U+FE0E (VS15) forces text
// presentation (☺︎ vs ☺); either one directly after a pictograph is part of a
// visible glyph, not a hidden variation-selector run.
const PRESENTATION_SELECTORS = new Set([0xfe0e, 0xfe0f]);

// ─── Emoji tag sequences (subregional flags) ─────────────────────────────────
// A subregional flag (🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland, 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales, 🏴󠁧󠁢󠁥󠁮󠁧󠁿 England …) is a WAVING
// BLACK FLAG tag_base (U+1F3F4, a visible pictograph) followed by one or more
// tag characters in U+E0020–U+E007E, terminated by U+E007F CANCEL TAG. Only that
// exact grammar is preserved verbatim; any tag char (the whole U+E0000–U+E007F
// block is category Cf) NOT inside a well-formed 🏴 … CANCEL run stays stripped —
// tag chars are the top ASCII-smuggling vector, so preservation fails CLOSED on a
// malformed/partial run.
const TAG_BASE = 0x1f3f4; // WAVING BLACK FLAG
const TAG_CANCEL = 0xe007f; // CANCEL TAG (the required terminator)
const TAG_SPEC_MIN = 0xe0020; // first tag char a flag sequence may carry
const TAG_SPEC_MAX = 0xe007e; // last tag char a flag sequence may carry
// A tag char decodes to ASCII (cp − 0xE0000), so a grammatically-valid
// 🏴 … CANCEL run can spell ARBITRARY ASCII ("ignore rules") and, if preserved
// only on grammar, smuggle it verbatim to the model. Preservation is therefore
// gated on the decoded payload naming a REGISTERED subdivision (the only tag
// sequences that render as a real flag) and on a tag-char cap — every other
// run, however well-formed, stays stripped (fail closed on the top ASCII vector).
const REGISTERED_TAG_PAYLOADS = new Set(["gbeng", "gbsct", "gbwls"]);
// Longest registered subdivision payload is 5 tag chars; cap a touch above it so
// a malformed-but-registered-prefix run can never carry a long ASCII rider.
const MAX_TAG_SPEC_CHARS = 6;

// ─── Ideographic variation selectors (VS17–VS256, U+E0100–U+E01EF) ────────────
// An ideographic variation sequence is a CJK ideograph followed by a selector in
// U+E0100–U+E01EF. Preserved ONLY when the immediately preceding code point is a
// CJK ideograph — the registry-faithful structural gate (IVS apply to ideographs
// and nothing else).
//
// Derived from Unicode's own data rather than hand-transcribed block spans: the
// Unified_Ideograph property IS the set of unified ideographs (URO + every
// extension), versioned with the runtime's ICU, so a new extension arrives with
// the Node upgrade instead of waiting for someone to notice. A hand-written
// table went stale exactly this way — it stopped at Extension H and so denied
// the 4,298 Extension J ideographs (U+323B0–U+33479) a legitimate IVS base.
//
// Script=Han is deliberately NOT used: it also covers radicals (U+2E80–U+2EF3),
// Kangxi radicals, U+3005/U+3007 and the ideographic-description characters,
// none of which is an IVS base. Script_Extensions=Han is wider still (it reaches
// U+00B7 MIDDLE DOT and the CJK punctuation shared with Kana), so it would let a
// full stop anchor a variation selector.
//
// The two Compatibility Ideograph BLOCKS stay literal: they are not
// Unified_Ideograph, and JS RegExp exposes no \p{Block=…}. Block boundaries are
// immutable by Unicode's stability policy, so a literal span cannot drift; the
// contract test in test/invisible-unicode-tables.test.mjs pins that every
// ASSIGNED code point inside them is a Script=Han letter.
const IVS_MIN = 0xe0100;
const IVS_MAX = 0xe01ef;
const CJK_IDEOGRAPH_RE =
  /[\p{Unified_Ideograph}\u{F900}-\u{FAFF}\u{2F800}-\u{2FA1F}]/u;

/** True when `ch` is a CJK ideograph (the only base an ideographic variation
 * selector legitimately follows). @param {string} ch @returns {boolean} */
function isCjkIdeograph(ch) {
  return CJK_IDEOGRAPH_RE.test(ch);
}

// Brahmic consonants: the only base a virama does half-form/conjunct work on.
// A bare or base-less halant + ZWJ carries no rendering and is a smuggling
// channel, so the Indic joiner is preserved only over one of these.
//
// The spans are GENERATED from the UCD (Indic_Syllabic_Category=Consonant,
// restricted by Script) and live in ./joining-type.mjs alongside the virama
// table they are read against — see scripts/gen-joining-type.mjs. They used to
// be hand-typed per-block KA–HA approximations here, which swept up the holes
// between the real consonants; ECMAScript exposes no
// \p{Indic_Syllabic_Category=…} escape, and \p{Script=Devanagari} is the wrong
// shape on its own (it also holds the independent vowels U+0904–U+0914, which a
// virama never attaches to), so a generated table is the only drift-proof
// answer. Re-exported here because it was part of this module's surface before
// it moved, and because test/invisible-unicode-tables.test.mjs checks each span
// against the script it claims.
export { BRAHMIC_CONSONANT_RANGES } from "./joining-type.mjs";

/** True when `ch` is a Brahmic consonant. Takes a CHARACTER, like its sibling
 * predicates here (`isCjkIdeograph`, `isJoinControl`), over the code-point
 * `isBrahmicConsonant` it wraps in ./joining-type.mjs, where every predicate
 * takes a code point.
 * @param {string} ch @returns {boolean} */
function isBrahmicConsonantChar(ch) {
  return (
    ch !== "" && isBrahmicConsonant(/** @type {number} */ (ch.codePointAt(0)))
  );
}

// ─── Blank-filler carve-out (Braille / archaic Hangul) ───────────────────────
// U+2800 (BRAILLE PATTERN BLANK) and the Hangul fillers render blank, so a RUN
// of them is a hidden channel — but a lone one does real work in genuine Braille
// (the empty cell) or archaic-Korean text, where stripping it mangles content.
// Gate them like the joiner carve-out: preserve one only next to a real,
// script-appropriate visible neighbour (a non-blank Braille cell; a Hangul
// jamo/syllable). A run of fillers has only fillers for neighbours, so it fails
// the anchor and is stripped — the run-length gate falls out of the anchor. The
// zero-width Mn marks in BLANK_NON_CF (U+034F/17B4/17B5) have no such benign
// standalone use, so they are never preserved.
const BRAILLE_BLANK = 0x2800;
const HANGUL_FILLERS = new Set([0x115f, 0x1160, 0x3164, 0xffa0]);
// Code points that trigger the carve-out path for blank fillers (see
// needsCarveOut). Written as \u escapes: a raw blank-rendering byte in a regex
// literal is invisible to the eye and a correctness landmine for the next editor.
const GATED_BLANK_RE = new RegExp("[\\u115F\\u1160\\u2800\\u3164\\uFFA0]", "u");

// Script=Braille, from the runtime's Unicode data (identical to
// Script_Extensions=Braille — no character is shared with another script).
const BRAILLE_RE = /\p{Script=Braille}/u;

/** A real (non-blank) Braille cell — the anchoring neighbour for a U+2800 blank.
 * @param {string} ch @returns {boolean} */
function isBrailleCell(ch) {
  const cp = ch ? ch.codePointAt(0) : -1;
  return cp !== BRAILLE_BLANK && BRAILLE_RE.test(ch);
}

// Script=Hangul, straight from the runtime's Unicode data. NOT
// Script_Extensions=Hangul: that set also holds the CJK punctuation Korean text
// shares with Chinese and Japanese (U+3001 IDEOGRAPHIC COMMA, U+30FB KATAKANA
// MIDDLE DOT, U+FF61–U+FF65 …), so a Japanese middle dot would anchor — and
// thereby preserve — a Hangul filler in text with no Hangul in it at all.
const HANGUL_RE = /\p{Script=Hangul}/u;

/** A Hangul jamo/syllable (NOT itself one of the fillers) — the anchoring
 * neighbour for a Hangul filler. @param {string} ch @returns {boolean} */
function isHangul(ch) {
  const cp = ch ? /** @type {number} */ (ch.codePointAt(0)) : -1;
  if (HANGUL_FILLERS.has(cp)) return false; // a filler cannot anchor another filler
  return HANGUL_RE.test(ch);
}

// Non-global single-char classifiers (CHECKS carry `g`, whose lastIndex is
// stateful across `.test`). carveStrip uses these to attribute each removed
// char to its CHECKS category so `found` names exactly what was stripped.
const CHECK_ONE = CHECKS.map(
  ([code, re]) =>
    /** @type {[string, RegExp]} */ ([code, new RegExp(re.source, "u")]),
);

/**
 * The CHECKS category code (a CATEGORY value) a single code point belongs to,
 * or null when it is not payload-capable (an ordinary visible character).
 * @param {string} ch  one code point
 * @returns {string | null}
 */
function classify(ch) {
  for (const [code, re] of CHECK_ONE) if (re.test(ch)) return code;
  return null;
}

/** A cursive-joining letter: Joining_Type dual, right, or left. (C is a join
 * control, T is a transparent mark, U is non-joining — none is a letter that a
 * ZWNJ/ZWJ does rendering work between.)
 * @param {string} jt @returns {boolean} */
const isCursiveLetter = (jt) => jt === "D" || jt === "R" || jt === "L";

/** The Joining_Type of a single-code-point string, or "U" for "" (boundary).
 * @param {string} ch @returns {string} */
const jtOf = (ch) =>
  ch ? joiningType(/** @type {number} */ (ch.codePointAt(0))) : "U";

/** True when `ch` is itself a ZWNJ/ZWJ (used to reject joiner runs).
 * @param {string} ch @returns {boolean} */
function isJoinControl(ch) {
  const cp = ch ? ch.codePointAt(0) : -1;
  return cp === ZWNJ || cp === ZWJ;
}

/**
 * The nearest neighbour of index `i` in direction `dir`, skipping Transparent
 * (combining-mark) code points, as the Unicode cursive-joining algorithm does —
 * a harakat between a letter and a ZWNJ does not break the join. Also skips any
 * OTHER tracked invisible that is itself removable (blank fillers, format
 * chars): it does no cursive-shaping work and gets stripped, so a joiner's real
 * neighbour is the next surviving character. Without this a payload byte wedged
 * between two joiners hides the joiner-RUN until a first pass removes it, after
 * which a second pass strips the now-adjacent joiners — non-idempotent. Join
 * controls (ZWNJ/ZWJ) are deliberately NOT skipped: they are the run signal.
 * Returns "" past the string boundary.
 * @param {string[]} cps @param {number} i @param {number} dir  -1 or +1
 * @returns {string}
 */
function effectiveNeighbor(cps, i, dir) {
  for (let j = i + dir; j >= 0 && j < cps.length; j += dir) {
    const ch = cps[j];
    if (jtOf(ch) === "T") continue;
    if (!isJoinControl(ch) && classify(ch) !== null) continue;
    return ch;
  }
  return "";
}

/**
 * True when the joiner at `cps[i]` follows a virama that itself sits on a real
 * Brahmic consonant — a genuine half-form/conjunct request (क् + ZWJ), not a
 * bare or base-less halant (a smuggling channel a raw `cps[i-1]` virama test
 * would wave through). Steps left over removable invisibles to LAND on the
 * virama (which is Joining_Type Transparent, so it is the anchor, never skipped),
 * then uses effectiveNeighbor to find the consonant base past any transparent
 * marks / invisibles between it and the virama.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function followsBrahmicConjunct(cps, i) {
  let j = i - 1;
  while (j >= 0 && !isJoinControl(cps[j]) && classify(cps[j]) !== null) j--;
  if (j < 0 || !isVirama(/** @type {number} */ (cps[j].codePointAt(0))))
    return false;
  return isBrahmicConsonantChar(effectiveNeighbor(cps, j, -1));
}

/**
 * True when the joiner at `cps[i]` does real rendering work and so must be
 * preserved rather than stripped, decided from the neighbours' Joining_Type:
 *   - emoji ZWJ: between two emoji components (its left pictograph may sit behind
 *     a VS16, so step over selectors — see leftNonSelector);
 *   - Indic joiner: after a virama that sits on a real Brahmic consonant;
 *   - Arabic-family joiner: between two cursive letters (ZWNJ needs both, ZWJ at
 *     least one — it forces a connected form). A joiner whose effective neighbour
 *     is ANOTHER joiner is a run (a zero-width payload channel) and is rejected.
 * Leading/trailing joiners fall out because "" has Joining_Type U.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function isPreservedJoiner(cps, i) {
  const cp = /** @type {number} */ (cps[i].codePointAt(0));
  if (cp !== ZWNJ && cp !== ZWJ) return false;
  // Emoji ZWJ sequences use ZWJ only; the real neighbours are the pictographs,
  // which may each sit behind a variation selector (🏳️‍🌈 = base VS16 ZWJ rainbow;
  // a selector can also follow the ZWJ before the next base), so step over
  // selectors on BOTH sides — leftNonSelector and its mirror rightNonSelector.
  if (
    cp === ZWJ &&
    EMOJI_LEFT.test(leftNonSelector(cps, i)) &&
    EMOJI_BASE.test(rightNonSelector(cps, i))
  )
    return true;
  // Indic: meaningful only after a virama sitting on a real consonant base.
  if (followsBrahmicConjunct(cps, i)) return true;
  // Arabic-family cursive joining, on the nearest non-Transparent neighbours.
  const left = effectiveNeighbor(cps, i, -1);
  const right = effectiveNeighbor(cps, i, 1);
  if (isJoinControl(left) || isJoinControl(right)) return false; // joiner run
  const lc = isCursiveLetter(jtOf(left));
  const rc = isCursiveLetter(jtOf(right));
  return cp === ZWNJ ? lc && rc : lc || rc;
}

/**
 * True when `cps[i]` is a presentation selector (VS15 U+FE0E or VS16 U+FE0F)
 * that is part of a visible glyph, not a hidden VS run:
 *   - directly after a pictograph/skin-tone modifier, preserved; OR
 *   - directly after a keycap base (digit/`#`/`*`) AND immediately followed by
 *     U+20E3 COMBINING ENCLOSING KEYCAP — a complete keycap glyph (1️⃣ #️⃣ …).
 * A keycap base + selector with NO trailing U+20E3 is a bare hidden presentation
 * selector, so it fails closed and is stripped. A longer selector run still
 * surfaces: the next selector's left neighbour is itself a selector.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function isEmojiPresentationSelector(cps, i) {
  if (
    !PRESENTATION_SELECTORS.has(/** @type {number} */ (cps[i].codePointAt(0)))
  )
    return false;
  const prev = cps[i - 1] ?? "";
  if (EMOJI_LEFT.test(prev)) return true;
  return (
    KEYCAP_BASE.test(prev) &&
    (cps[i + 1]?.codePointAt(0) ?? -1) === COMBINING_KEYCAP
  );
}

/**
 * Per-invisible carve-out analysis, shared by carveStrip and
 * countPayloadInvisible: for each code point, its CHECKS category (null when
 * visible) and its preserve `kind` ("joiner" | "emojivs" | "tag" | "stdvs" |
 * "ivs" | "blank" | null). Everything invisible that is NOT preserve-eligible is
 * payload; the scatter floor counts only that, so meaningful joiners/selectors
 * never push honest prose over the threshold.
 * @param {string[]} cps
 * @returns {{ codes: (string|null)[], kind: (string|null)[], payloadInvis: number, visibleLen: number }}
 */
function analyzeCarve(cps) {
  const codes = cps.map(classify);
  const tagKeep = markTagSequences(cps);
  const kind = cps.map((_, i) => {
    if (codes[i] === null) return null;
    if (tagKeep[i]) return "tag";
    if (isPreservedJoiner(cps, i)) return "joiner";
    if (isEmojiPresentationSelector(cps, i)) return "emojivs";
    if (isStandardizedVariationSelector(cps, i)) return "stdvs";
    if (isIdeographicVariationSelector(cps, i)) return "ivs";
    if (isPreservedBlankFiller(cps, i)) return "blank";
    return null;
  });
  let payloadInvis = 0;
  let visibleLen = 0;
  for (let i = 0; i < cps.length; i++) {
    if (codes[i] === null) visibleLen++;
    else if (kind[i] === null) payloadInvis++;
  }
  return { codes, kind, payloadInvis, visibleLen };
}

/**
 * Count the PAYLOAD invisible code points in `text`: those the carve-out would
 * strip, excluding ZWNJ/ZWJ (and emoji VS16) that do real rendering work.
 * Consumers that gate on invisible density (e.g. the prompt classifier's scatter
 * threshold) use this so legitimate dense multilingual prose is not mistaken for
 * a hidden channel.
 * @param {string} text
 * @returns {number}
 */
export function countPayloadInvisible(text) {
  return analyzeCarve(Array.from(text)).payloadInvis;
}

/**
 * Bulk strip (the common path: {@link needsCarveOut} found nothing the
 * carve-out could apply to). A single regex pass removes every payload-
 * capable char; `found` names the category codes present via `.search`
 * (which ignores the `g` lastIndex).
 * @param {string} body
 * @returns {{ cleaned: string, found: string[] }}
 */
function bulkStrip(body) {
  const found = CHECKS.filter(([, re]) => body.search(re) !== -1).map(
    ([code]) => code,
  );
  return { cleaned: body.replace(STRIP, ""), found };
}

/**
 * The nearest code point left of index `i` that is not a variation selector, or
 * "" at the string start. An emoji ZWJ sequence can place a VS16 between the base
 * pictograph and the ZWJ, so the joiner's real left neighbor is found by stepping
 * over any variation selector(s).
 * @param {string[]} cps
 * @param {number} i
 * @returns {string}
 */
function leftNonSelector(cps, i) {
  let p = i - 1;
  while (p >= 0 && VARIATION_SELECTOR.test(cps[p])) p--;
  return cps[p] ?? "";
}

/**
 * The nearest code point right of index `i` that is not a variation selector, or
 * "" at the string end. Mirror of {@link leftNonSelector}: an emoji ZWJ can be
 * followed by a selector before the next component's base pictograph, so the
 * joiner's real right neighbor is found by stepping over any variation
 * selector(s).
 * @param {string[]} cps
 * @param {number} i
 * @returns {string}
 */
function rightNonSelector(cps, i) {
  let p = i + 1;
  while (p < cps.length && VARIATION_SELECTOR.test(cps[p])) p++;
  return cps[p] ?? "";
}

/**
 * Mark every index that belongs to a PRESERVABLE emoji tag sequence (subregional
 * flag): a U+1F3F4 tag_base, then tag chars in U+E0020–U+E007E whose decoded
 * ASCII payload names a REGISTERED subdivision, then U+E007F CANCEL TAG. Only the
 * tag chars and the terminating CANCEL are marked (the base is a visible
 * pictograph). A run missing the CANCEL, exceeding the tag-char cap, or whose
 * payload is not a registered subdivision is left unmarked so it is stripped —
 * grammatical validity alone is NOT enough, since a valid run spells arbitrary
 * ASCII (fail closed on the top ASCII-smuggling vector).
 * @param {string[]} cps
 * @returns {boolean[]} keep[i] true iff `cps[i]` is inside a preservable tag sequence
 */
function markTagSequences(cps) {
  const keep = new Array(cps.length).fill(false);
  /** @param {number} k @returns {number} */
  const cpAt = (k) => /** @type {number} */ (cps[k].codePointAt(0));
  for (let i = 0; i < cps.length; i++) {
    if (cpAt(i) !== TAG_BASE) continue;
    let j = i + 1;
    let payload = "";
    while (
      j < cps.length &&
      cpAt(j) >= TAG_SPEC_MIN &&
      cpAt(j) <= TAG_SPEC_MAX
    ) {
      payload += String.fromCharCode(cpAt(j) - 0xe0000);
      j++;
    }
    const tagLen = j - (i + 1);
    // Require ≥1 tag char, at most MAX_TAG_SPEC_CHARS, a terminating CANCEL, and
    // a payload naming a registered subdivision — else the run stays stripped.
    if (
      tagLen >= 1 &&
      tagLen <= MAX_TAG_SPEC_CHARS &&
      j < cps.length &&
      cpAt(j) === TAG_CANCEL &&
      REGISTERED_TAG_PAYLOADS.has(payload)
    ) {
      for (let k = i + 1; k <= j; k++) keep[k] = true;
      i = j; // resume after the consumed sequence
    }
  }
  return keep;
}

/**
 * True when `cps[i]` is a standardized variation selector (U+FE00–U+FE0D) whose
 * immediately preceding code point forms a REGISTERED standardized variation
 * sequence (per the generated UCD table). Every unregistered FE00–FE0D selector
 * stays payload.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function isStandardizedVariationSelector(cps, i) {
  const cp = /** @type {number} */ (cps[i].codePointAt(0));
  if (cp < 0xfe00 || cp > 0xfe0d) return false;
  const prev = cps[i - 1];
  return prev
    ? isStandardizedVariant(/** @type {number} */ (prev.codePointAt(0)), cp)
    : false;
}

/**
 * True when `cps[i]` is an ideographic variation selector (VS17–VS256,
 * U+E0100–U+E01EF) immediately after a CJK ideograph — the registry-faithful
 * structural gate for an ideographic variation sequence.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function isIdeographicVariationSelector(cps, i) {
  const cp = /** @type {number} */ (cps[i].codePointAt(0));
  if (cp < IVS_MIN || cp > IVS_MAX) return false;
  return isCjkIdeograph(cps[i - 1] ?? "");
}

/**
 * True when `cps[i]` is a Braille blank (U+2800) or a Hangul filler that sits
 * next to a real, script-appropriate visible neighbour — a genuine empty Braille
 * cell or archaic-Korean filler, not a hidden run. The zero-width Mn marks in
 * BLANK_NON_CF have no such anchored use and are never preserved here.
 * @param {string[]} cps @param {number} i
 * @returns {boolean}
 */
function isPreservedBlankFiller(cps, i) {
  const cp = /** @type {number} */ (cps[i].codePointAt(0));
  const prev = cps[i - 1] ?? "";
  const next = cps[i + 1] ?? "";
  if (cp === BRAILLE_BLANK) return isBrailleCell(prev) || isBrailleCell(next);
  if (HANGUL_FILLERS.has(cp)) return isHangul(prev) || isHangul(next);
  return false;
}

// The grapheme segmenter: the real UAX #29 implementation shipped with the
// runtime's ICU, not a hand-rolled approximation of cluster boundaries. It
// defines the unit the preserve budget is charged against (see carveStrip).
// Grapheme segmentation is locale-independent, so the locale is pinned to "en"
// only for determinism across hosts.
const GRAPHEME_SEGMENTER = new Intl.Segmenter("en", {
  granularity: "grapheme",
});

/**
 * The code-point index one past the end of each grapheme cluster of `body`, in
 * order — the segmenter's UTF-16 boundaries restated in code-point space, which
 * is the space `carveStrip`'s per-code-point arrays live in. ECMA-402 guarantees
 * the segments partition the input, so the last entry is always the code-point
 * length of `body`.
 * @param {string} body
 * @returns {number[]}
 */
function clusterEnds(body) {
  const ends = [];
  let end = 0;
  for (const { segment } of GRAPHEME_SEGMENTER.segment(body)) {
    end += Array.from(segment).length;
    ends.push(end);
  }
  return ends;
}

/**
 * Carve-out strip (an invisible the carve-out might preserve is present): walk
 * GRAPHEME CLUSTERS, preserving a cluster's joiners/selectors/tags/blank-fillers
 * only where each has its `kind` set AND the text stays under the scatter floor
 * AND the whole cluster fits inside the remaining per-run
 * (CONSECUTIVE_JOINER_CAP / CONSECUTIVE_SELECTOR_CAP) and document-wide
 * (TOTAL_PRESERVED_JOINER_BUDGET) preserve allowance — otherwise every
 * preservable char in that cluster is stripped like any other payload byte.
 *
 * The budget is charged against the CLUSTER, not the code point, because the
 * cluster is the indivisible unit: charging per code point let a limit fall due
 * mid-cluster and carve one grapheme in half (👨‍👩‍👧‍👦 with the budget exhausted
 * after its first ZWJ came out as 👨‍👩👧👦 — three glyphs where the author wrote
 * one). All-or-nothing per cluster makes that impossible by construction rather
 * than merely unlikely, and it subsumes the tag (subregional-flag) sequence's
 * hand-rolled atomicity: a flag's tag chars are Grapheme_Cluster_Break=Extend,
 * so they are already inside their base pictograph's cluster.
 *
 * `found` reports only categories actually removed, so a preserved char never
 * makes the caller claim a strip that did not happen, and a stuffed channel
 * surfaces as its category once it overruns the budget.
 * @param {string} body
 * @returns {{ cleaned: string, found: string[] }}
 */
function carveStrip(body) {
  const cps = Array.from(body);
  // Pass 1: classify + evaluate the gate once (see analyzeCarve). Only PAYLOAD
  // invisibles count toward the scatter floor, so a meaningful-joiner-dense text
  // (formal Persian, a long Devanagari conjunct run) stays under it.
  const { codes, kind, payloadInvis, visibleLen } = analyzeCarve(cps);
  // SCATTERED_THRESHOLD is the floor on payload invisibles: past it the document
  // is drowning in hidden bytes, so the carve-out is off and even a meaningful
  // joiner is stripped (threshold-evasion catch — over-strip beats under).
  const allowCarveOut = payloadInvis < SCATTERED_THRESHOLD;
  // Document-wide preserve allowance, proportional to visible text but never
  // below the floor (see TOTAL_PRESERVED_JOINER_BUDGET / PRESERVED_JOINER_PER_VISIBLE)
  // and never above PRESERVE_HARD_CAP — the absolute ceiling stops the channel
  // scaling with attacker-supplied cover text.
  const maxPreserved = Math.min(
    PRESERVE_HARD_CAP,
    Math.max(
      TOTAL_PRESERVED_JOINER_BUDGET,
      Math.ceil(visibleLen / PRESERVED_JOINER_PER_VISIBLE),
    ),
  );

  const foundCodes = new Set();
  let out = "";
  // Preserved JOINERS in the current uninterrupted cluster (tags/blank fillers
  // and presentation selectors don't chain, so they are exempt). A genuine gap
  // (two visible chars in a row — see prevVisible) resets it; past the cap the
  // surplus is stripped.
  let joinerRun = 0;
  // Preserved IVS/standardized variation selectors in the current uninterrupted
  // run (an `ideograph selector ideograph selector …` chain never breaks the
  // prevVisible gap, so joinerRun's reset does not bound it — this counter does).
  // Same genuine-gap reset as joinerRun; past CONSECUTIVE_SELECTOR_CAP the
  // surplus is stripped, closing the high-bit-rate variation-selector channel.
  let selectorRun = 0;
  // Preserved chars across the WHOLE string — never reset at a gap, so it bounds
  // the document-wide channel joinerRun cannot. Past maxPreserved a preserved
  // char is stripped and its category reported.
  let preservedTotal = 0;
  let prevVisible = false;
  let start = 0;
  for (const end of clusterEnds(body)) {
    // Charge the WHOLE cluster's preservables against every limit at once: if
    // any one of them would fall due part-way through, none of the cluster is
    // preserved. `need === 0` (the common case: a cluster with no preservable
    // invisible) leaves every counter untouched.
    let need = 0;
    let joiners = 0;
    let selectors = 0;
    for (let k = start; k < end; k++) {
      if (kind[k] === null) continue;
      need++;
      if (kind[k] === "joiner") joiners++;
      if (kind[k] === "ivs" || kind[k] === "stdvs") selectors++;
    }
    // The run counters as they stand at the cluster's FIRST preservable char.
    // A cluster can OPEN with a genuine gap — two visible code points in a row,
    // e.g. the second of two adjacent emoji ZWJ sequences, or a letter and its
    // harakat — which the emit loop resets on a few lines below. Judging the
    // caps on the stale pre-reset count would strip joiners the cap never meant
    // to catch: a false positive on legitimate joined text. This mirrors the
    // emit loop's gap rule exactly (only a visible char after another visible
    // char closes a run; any invisible, payload included, does not) and stops at
    // the first preservable, since resets past it are the emit loop's business.
    let runJoiner = joinerRun;
    let runSelector = selectorRun;
    let seenVisible = prevVisible;
    for (let k = start; k < end && kind[k] === null; k++) {
      if (codes[k] === null && seenVisible) {
        runJoiner = 0;
        runSelector = 0;
      }
      seenVisible = codes[k] === null;
    }
    const fits =
      allowCarveOut &&
      preservedTotal + need <= maxPreserved &&
      runJoiner + joiners <= CONSECUTIVE_JOINER_CAP &&
      runSelector + selectors <= CONSECUTIVE_SELECTOR_CAP;
    for (let k = start; k < end; k++) {
      const code = codes[k];
      if (code === null) {
        // A visible char following another visible char is a real word/segment
        // boundary, not a join — the joined cluster (if any) ended here.
        if (prevVisible) {
          joinerRun = 0;
          selectorRun = 0;
        }
        prevVisible = true;
        out += cps[k]; // ordinary visible character
        continue;
      }
      if (fits && kind[k] !== null) {
        if (kind[k] === "joiner") joinerRun++;
        if (kind[k] === "ivs" || kind[k] === "stdvs") selectorRun++;
        preservedTotal++;
        prevVisible = false; // a joiner/selector/tag keeps the cluster open
        out += cps[k];
        continue;
      }
      foundCodes.add(code);
      prevVisible = false; // a stripped invisible neither opens nor closes a gap
    }
    start = end;
  }
  const found = CHECKS.filter(([code]) => foundCodes.has(code)).map(
    ([code]) => code,
  );
  return { cleaned: out, found };
}

// Any tag char (the whole U+E0000–U+E007F block is category Cf).
const TAG_CHAR_RE = /[\u{E0000}-\u{E007F}]/u;

/**
 * True when `body` holds anything the carve-out in {@link carveStrip} might
 * preserve: a ZWNJ/ZWJ, ANY variation selector (a registered standardized or
 * ideographic sequence, or an emoji presentation selector — VARIATION_SELECTOR
 * covers FE00–FE0F and E0100–E01EF), a tag char (a subregional flag), or a
 * gated blank filler (Braille/archaic-Hangul). Each needs the per-neighbor
 * analysis, or bulkStrip would strip it unconditionally and corrupt a
 * legitimate glyph.
 * @param {string} body
 * @returns {boolean}
 */
function needsCarveOut(body) {
  return (
    body.includes(String.fromCodePoint(ZWNJ)) ||
    body.includes(String.fromCodePoint(ZWJ)) ||
    VARIATION_SELECTOR.test(body) ||
    TAG_CHAR_RE.test(body) ||
    GATED_BLANK_RE.test(body)
  );
}

/**
 * The `text` with every carve-out-PRESERVABLE invisible (joiners/selectors/tags/
 * blank fillers doing real rendering work) replaced by a space, leaving only the
 * PAYLOAD invisibles in place. The LONG_RUN injection probe runs over this so a
 * legitimate emoji/flag/variation sequence never trips the "possible injection
 * payload" marker (alert fatigue), while a genuine hidden run still surfaces.
 * @param {string} text
 * @returns {string}
 */
export function payloadInvisibleView(text) {
  const cps = Array.from(text);
  const { codes, kind } = analyzeCarve(cps);
  let out = "";
  for (let i = 0; i < cps.length; i++)
    out += codes[i] !== null && kind[i] === null ? cps[i] : " ";
  return out;
}

/**
 * Strip payload-capable invisible chars and report which categories were
 * removed. A single leading U+FEFF (BOM) is preserved as a legitimate marker;
 * interior BOMs and all soft hyphens (U+00AD) are stripped, since either can
 * encode hidden instructions. ZWNJ/ZWJ survive only in a linguistic context
 * (see the carve-out above). `found` names exactly the categories stripped, so
 * a caller never warns about a strip the carve-out skipped.
 *
 * `originalText` is the pre-processing text (before any ANSI strip) used ONLY to
 * decide whether a leading BOM is genuinely leading: an interior BOM that an
 * ANSI-strip left at index 0 of `text` (e.g. `ESC[m + interior U+FEFF`) must NOT be treated as a
 * legitimate leading marker. Defaults to `text` for the common single-arg call.
 * @param {string} text
 * @param {string} [originalText]
 * @returns {{ cleaned: string, found: string[] }}
 */
export function stripInvisibleWithReport(text, originalText = text) {
  // Leading only when the BOM leads the ORIGINAL text (not merely `text` after an
  // ANSI strip shifted an interior BOM to index 0). The `text` guard keeps the
  // slice sound when the two disagree.
  const hasLeadingBom =
    originalText.charCodeAt(0) === 0xfeff && text.charCodeAt(0) === 0xfeff;
  const body = hasLeadingBom ? text.slice(1) : text;
  const { cleaned, found } = needsCarveOut(body)
    ? carveStrip(body)
    : bulkStrip(body);
  return { cleaned: hasLeadingBom ? BOM + cleaned : cleaned, found };
}

/**
 * Strip payload-capable invisible chars (cleaned text only). See
 * stripInvisibleWithReport for the BOM and ZWNJ/ZWJ carve-out semantics.
 * @param {string} text
 * @returns {string}
 */
export function stripInvisible(text) {
  return stripInvisibleWithReport(text).cleaned;
}
